-- Script Run On PENSBI SCHEMA

DROP TABLE XXPENS_BI_RUNNING_STATUS;

CREATE TABLE XXPENS_BI_RUNNING_STATUS
(RUNNING_ID   NUMBER
,START_DATE   DATE
,END_DATE     DATE);

CREATE SEQUENCE XXPENS_BI_RUNNING_STATUS_SEQ;

SELECT XXPENS_BI_RUNNING_STATUS_SEQ.NEXTVAL FROM DUAL;

GRANT INSERT , UPDATE , SELECT ON XXPENS_BI_RUNNING_STATUS TO APPS;

INSERT INTO XXPENS_BI_RUNNING_STATUS(RUNNING_ID,START_DATE) VALUES (1,SYSDATE);


---- Run The Follow Script On Apps
CREATE OR REPLACE SYNONYM "APPS"."XXPENS_BI_RUNNING_STATUS" FOR "PENSBI"."XXPENS_BI_RUNNING_STATUS";

CREATE OR REPLACE SYNONYM "APPS"."XXPENS_BI_RUNNING_STATUS_SEQ" FOR "PENSBI"."XXPENS_BI_RUNNING_STATUS_SEQ";


GRANT SELECT ON XXPENS_BI_RUNNING_STATUS_SEQ TO APPS;