ALTER TABLE `m_customer` MODIFY COLUMN `AGE_MONTH` INTEGER UNSIGNED NOT NULL DEFAULT 0,
ADD COLUMN `PAYMENT_TYPE` INTEGER AFTER `CREDITCARD_EXPIRED`,
ADD COLUMN `FREE_OF_CHART` VARCHAR(1) DEFAULT 'N' AFTER `PAYMENT_TYPE` ;
 
ALTER TABLE `t_order_line` ADD COLUMN `NEED_BILL` DECIMAL(15,5) AFTER `CALL_BEFORE_SEND`;

ALTER TABLE `t_order_line` MODIFY COLUMN `TRIP_NO` INTEGER UNSIGNED DEFAULT 0,
 ADD COLUMN `PAYMENT_TYPE` INTEGER AFTER `NEED_BILL`;
 
ALTER TABLE `t_order_line` ADD COLUMN `PAYMENT_METHOD` VARCHAR(5) AFTER `PAYMENT_TYPE`;

ALTER TABLE `t_order_line` ADD COLUMN `PROMOTION1` CHAR(1) DEFAULT 'N' AFTER `PAYMENT_METHOD`;

ALTER TABLE `t_order_line` ADD COLUMN `SHIPMENT` CHAR(1) AFTER `PROMOTION1`;

ALTER TABLE `t_order_line` ADD COLUMN `COMMENT` VARCHAR(45) AFTER `SHIPMENT`;

ALTER TABLE `t_order_line` ADD COLUMN `ACTUAL_QTY` DECIMAL(10,2) AFTER `COMMENT`;

ALTER TABLE `t_order_line` ADD COLUMN `RECEIPT` CHAR(1) AFTER `ACTUAL_QTY`;

ALTER TABLE `t_order_line` ADD COLUMN `ACT_NEED_BILL` DECIMAL(15,5) AFTER `RECEIPT`;

ALTER TABLE `t_receipt_line` ADD COLUMN `PREPAID` VARCHAR(1) AFTER `DESCRIPTION`;
