drop TABLE t_bill_plan;
CREATE TABLE t_bill_plan (
	bill_plan_no varchar(30) NOT NULL,
	bill_plan_date date NOT NULL,
	bill_plan_request_date date,
	sales_code varchar(20) NOT NULL,
	pd_code varchar(20) NOT NULL,
	status varchar(2),
	exported char(1),
	description varchar(240),
	USER_ID int(10),
	CREATED date,
	CREATED_BY varchar(20),
	UPDATED date,
	UPDATED_BY varchar(20),
	PRIMARY KEY (bill_plan_no)
)ENGINE=InnoDB DEFAULT CHARSET=tis620;

drop TABLE t_bill_plan_line;
CREATE TABLE t_bill_plan_line (
    bill_plan_no varchar(30) NOT NULL,
	product_id int NOT NULL,
	qty decimal(15,5) NOT NULL,
	uom varchar(20) NOT NULL,
	CREATED date,
	CREATED_BY varchar(20),
	UPDATED date,
	UPDATED_BY varchar(20),
	PRIMARY KEY (bill_plan_no,product_id)
)ENGINE=InnoDB DEFAULT CHARSET=tis620;

/** FK  product_id **/
ALTER TABLE m_sales_target_new
DROP FOREIGN KEY m_sales_target_new_ibfk_1;

/** FK product_id **/
ALTER TABLE m_sales_target_new
DROP FOREIGN KEY m_sales_target_new_ibfk_3;

/** customer_id **/
ALTER TABLE m_trip
DROP FOREIGN KEY m_trip_ibfk_1;

/** FK customer_id **/
ALTER TABLE t_order
DROP FOREIGN KEY t_order_ibfk_1;

/** FK pricelist_id **/
ALTER TABLE t_order
DROP FOREIGN KEY t_order_ibfk_3;

/** FK product_id **/
ALTER TABLE t_order_line
DROP FOREIGN KEY t_order_line_ibfk_2;

/** FK uom_id **/
ALTER TABLE t_order_line
DROP FOREIGN KEY t_order_line_ibfk_3;

/** FK customer_id **/
ALTER TABLE t_receipt
DROP FOREIGN KEY t_receipt_ibfk_2;

/** FK customer_id **/
ALTER TABLE t_visit
DROP FOREIGN KEY t_visit_ibfk_1;

/** FK product_id **/
ALTER TABLE t_visit_line
DROP FOREIGN KEY t_visit_line_ibfk_2;

/** FK uom_id **/
ALTER TABLE t_visit_line
DROP FOREIGN KEY t_visit_line_ibfk_3;

/** FK uom_id **/
ALTER TABLE m_modifier_attr
DROP FOREIGN KEY m_modifier_attr_ibfk_2;

/** FK pricelist_id **/
ALTER TABLE m_modifier_line
DROP FOREIGN KEY m_modifier_line_ibfk_2;

/** FK uom_id **/
ALTER TABLE m_modifier_line
DROP FOREIGN KEY m_modifier_line_ibfk_3;

/** FK uom_id **/
ALTER TABLE m_product
DROP FOREIGN KEY m_product_ibfk_1;

/** FK product_category_id **/
ALTER TABLE m_product
DROP FOREIGN KEY m_product_ibfk_2;

/** FK pricelist_id **/
ALTER TABLE m_product_price
DROP FOREIGN KEY m_product_price_ibfk_1;

/** FK product_id **/
ALTER TABLE m_product_price
DROP FOREIGN KEY m_product_price_ibfk_2;

/** FK product_id **/
ALTER TABLE m_uom_class_conversion
DROP FOREIGN KEY m_uom_class_conversion_ibfk_1;

/** FK uom_from_id **/
ALTER TABLE m_uom_class_conversion
DROP FOREIGN KEY m_uom_class_conversion_ibfk_2;

/** FK uom_to_id **/
ALTER TABLE m_uom_class_conversion
DROP FOREIGN KEY m_uom_class_conversion_ibfk_3;

/** FK sub_inventory_id **/
ALTER TABLE m_inventory_onhand
DROP FOREIGN KEY m_inventory_onhand_ibfk_2;

/** FK product_id **/
ALTER TABLE m_inventory_onhand
DROP FOREIGN KEY m_inventory_onhand_ibfk_3;

/** FK uom_id **/
ALTER TABLE m_inventory_onhand
DROP FOREIGN KEY m_inventory_onhand_ibfk_4;

/** Check DiffDate **/
insert into c_reference (reference_id,code,name,description,value,isactive)
values(2201,'MoveOrder','ตรวสอบวันที่เบิกคืนสินค้า','ตรวจสอบวันที่เบิกสินค้าหากวันที่ระบุก่อนถึงสิ้นเดือน 2 วัน ให้ระบุเป็นวันที่ 1 เดือนหน้า',2,'Y');

insert into c_reference (reference_id,code,name,description,value,isactive)
values(2202,'BillPlan','ตรวสอบวันที่รับสินค้า','ตรวจสอบวันที่รับสินค้าหากวันที่ระบุก่อนถึงสิ้นเดือน 2 วัน ให้ระบุเป็นวันที่ 1 เดือนหน้า',2,'Y');

/** product unused TT **/

insert into m_product_unused(code,type)values(	'822013'	,'TT');
insert into m_product_unused(code,type)values(	'822014'	,'TT');
insert into m_product_unused(code,type)values(	'822015'	,'TT');
insert into m_product_unused(code,type)values(	'822016'	,'TT');
insert into m_product_unused(code,type)values(	'822017'	,'TT');
insert into m_product_unused(code,type)values(	'822018'	,'TT');
insert into m_product_unused(code,type)values(	'822019'	,'TT');
insert into m_product_unused(code,type)values(	'822020'	,'TT');
insert into m_product_unused(code,type)values(	'823001'	,'TT');
insert into m_product_unused(code,type)values(	'823002'	,'TT');
insert into m_product_unused(code,type)values(	'823003'	,'TT');
insert into m_product_unused(code,type)values(	'823004'	,'TT');
insert into m_product_unused(code,type)values(	'823005'	,'TT');
insert into m_product_unused(code,type)values(	'823006'	,'TT');
insert into m_product_unused(code,type)values(	'824001'	,'TT');
insert into m_product_unused(code,type)values(	'824002'	,'TT');
insert into m_product_unused(code,type)values(	'824003'	,'TT');
insert into m_product_unused(code,type)values(	'824004'	,'TT');
insert into m_product_unused(code,type)values(	'824005'	,'TT');
insert into m_product_unused(code,type)values(	'824006'	,'TT');
insert into m_product_unused(code,type)values(	'824007'	,'TT');
insert into m_product_unused(code,type)values(	'824008'	,'TT');
insert into m_product_unused(code,type)values(	'824009'	,'TT');
insert into m_product_unused(code,type)values(	'824010'	,'TT');
insert into m_product_unused(code,type)values(	'824011'	,'TT');
insert into m_product_unused(code,type)values(	'824012'	,'TT');
insert into m_product_unused(code,type)values(	'825001'	,'TT');
insert into m_product_unused(code,type)values(	'825002'	,'TT');
insert into m_product_unused(code,type)values(	'825003'	,'TT');
insert into m_product_unused(code,type)values(	'825004'	,'TT');
insert into m_product_unused(code,type)values(	'825005'	,'TT');
insert into m_product_unused(code,type)values(	'825006'	,'TT');
insert into m_product_unused(code,type)values(	'825007'	,'TT');
insert into m_product_unused(code,type)values(	'825008'	,'TT');
insert into m_product_unused(code,type)values(	'825009'	,'TT');
insert into m_product_unused(code,type)values(	'825010'	,'TT');
insert into m_product_unused(code,type)values(	'825011'	,'TT');
insert into m_product_unused(code,type)values(	'825012'	,'TT');
insert into m_product_unused(code,type)values(	'825013'	,'TT');
insert into m_product_unused(code,type)values(	'825014'	,'TT');
insert into m_product_unused(code,type)values(	'825015'	,'TT');
insert into m_product_unused(code,type)values(	'825016'	,'TT');
insert into m_product_unused(code,type)values(	'825017'	,'TT');
insert into m_product_unused(code,type)values(	'825018'	,'TT');
insert into m_product_unused(code,type)values(	'825019'	,'TT');
insert into m_product_unused(code,type)values(	'825020'	,'TT');
insert into m_product_unused(code,type)values(	'825021'	,'TT');
insert into m_product_unused(code,type)values(	'825022'	,'TT');
insert into m_product_unused(code,type)values(	'825023'	,'TT');
insert into m_product_unused(code,type)values(	'825024'	,'TT');
insert into m_product_unused(code,type)values(	'826001'	,'TT');
insert into m_product_unused(code,type)values(	'826002'	,'TT');
insert into m_product_unused(code,type)values(	'826003'	,'TT');
insert into m_product_unused(code,type)values(	'826004'	,'TT');
insert into m_product_unused(code,type)values(	'826005'	,'TT');
insert into m_product_unused(code,type)values(	'826006'	,'TT');
insert into m_product_unused(code,type)values(	'826007'	,'TT');
insert into m_product_unused(code,type)values(	'826008'	,'TT');
insert into m_product_unused(code,type)values(	'827001'	,'TT');
insert into m_product_unused(code,type)values(	'827002'	,'TT');
insert into m_product_unused(code,type)values(	'827003'	,'TT');
insert into m_product_unused(code,type)values(	'827004'	,'TT');
insert into m_product_unused(code,type)values(	'827005'	,'TT');
insert into m_product_unused(code,type)values(	'827006'	,'TT');
insert into m_product_unused(code,type)values(	'827007'	,'TT');
insert into m_product_unused(code,type)values(	'827008'	,'TT');
insert into m_product_unused(code,type)values(	'827009'	,'TT');
insert into m_product_unused(code,type)values(	'827010'	,'TT');
insert into m_product_unused(code,type)values(	'827011'	,'TT');
insert into m_product_unused(code,type)values(	'827012'	,'TT');
insert into m_product_unused(code,type)values(	'827013'	,'TT');
insert into m_product_unused(code,type)values(	'827014'	,'TT');
insert into m_product_unused(code,type)values(	'827015'	,'TT');
insert into m_product_unused(code,type)values(	'827016'	,'TT');
insert into m_product_unused(code,type)values(	'827017'	,'TT');
insert into m_product_unused(code,type)values(	'827018'	,'TT');
insert into m_product_unused(code,type)values(	'827019'	,'TT');
insert into m_product_unused(code,type)values(	'827020'	,'TT');
insert into m_product_unused(code,type)values(	'827021'	,'TT');
insert into m_product_unused(code,type)values(	'827022'	,'TT');
insert into m_product_unused(code,type)values(	'827023'	,'TT');
insert into m_product_unused(code,type)values(	'827024'	,'TT');
insert into m_product_unused(code,type)values(	'827025'	,'TT');
insert into m_product_unused(code,type)values(	'827026'	,'TT');
insert into m_product_unused(code,type)values(	'827027'	,'TT');
insert into m_product_unused(code,type)values(	'827028'	,'TT');
insert into m_product_unused(code,type)values(	'828001'	,'TT');
insert into m_product_unused(code,type)values(	'828002'	,'TT');
insert into m_product_unused(code,type)values(	'828003'	,'TT');
insert into m_product_unused(code,type)values(	'828004'	,'TT');
insert into m_product_unused(code,type)values(	'828005'	,'TT');
insert into m_product_unused(code,type)values(	'828006'	,'TT');
insert into m_product_unused(code,type)values(	'822001'	,'TT');
insert into m_product_unused(code,type)values(	'822002'	,'TT');
insert into m_product_unused(code,type)values(	'822003'	,'TT');
insert into m_product_unused(code,type)values(	'822004'	,'TT');
insert into m_product_unused(code,type)values(	'822005'	,'TT');
insert into m_product_unused(code,type)values(	'822006'	,'TT');
insert into m_product_unused(code,type)values(	'822007'	,'TT');
insert into m_product_unused(code,type)values(	'822008'	,'TT');
insert into m_product_unused(code,type)values(	'822009'	,'TT');
insert into m_product_unused(code,type)values(	'822010'	,'TT');
insert into m_product_unused(code,type)values(	'822011'	,'TT');
insert into m_product_unused(code,type)values(	'822012'	,'TT');
insert into m_product_unused(code,type)values(	'821001'	,'TT');
insert into m_product_unused(code,type)values(	'833032'	,'TT');
insert into m_product_unused(code,type)values(	'833033'	,'TT');
insert into m_product_unused(code,type)values(	'833034'	,'TT');
insert into m_product_unused(code,type)values(	'833035'	,'TT');
insert into m_product_unused(code,type)values(	'833036'	,'TT');
insert into m_product_unused(code,type)values(	'833037'	,'TT');
insert into m_product_unused(code,type)values(	'833038'	,'TT');
insert into m_product_unused(code,type)values(	'833039'	,'TT');
insert into m_product_unused(code,type)values(	'833040'	,'TT');
insert into m_product_unused(code,type)values(	'833041'	,'TT');
insert into m_product_unused(code,type)values(	'833042'	,'TT');
insert into m_product_unused(code,type)values(	'833043'	,'TT');
insert into m_product_unused(code,type)values(	'833080'	,'TT');
insert into m_product_unused(code,type)values(	'833081'	,'TT');
insert into m_product_unused(code,type)values(	'833082'	,'TT');
insert into m_product_unused(code,type)values(	'833083'	,'TT');
insert into m_product_unused(code,type)values(	'833084'	,'TT');
insert into m_product_unused(code,type)values(	'833085'	,'TT');
insert into m_product_unused(code,type)values(	'833086'	,'TT');
insert into m_product_unused(code,type)values(	'833087'	,'TT');
insert into m_product_unused(code,type)values(	'833088'	,'TT');
insert into m_product_unused(code,type)values(	'833089'	,'TT');
insert into m_product_unused(code,type)values(	'833090'	,'TT');
insert into m_product_unused(code,type)values(	'833091'	,'TT');
insert into m_product_unused(code,type)values(	'833044'	,'TT');
insert into m_product_unused(code,type)values(	'833045'	,'TT');
insert into m_product_unused(code,type)values(	'833046'	,'TT');
insert into m_product_unused(code,type)values(	'833047'	,'TT');
insert into m_product_unused(code,type)values(	'833048'	,'TT');
insert into m_product_unused(code,type)values(	'833049'	,'TT');
insert into m_product_unused(code,type)values(	'833050'	,'TT');
insert into m_product_unused(code,type)values(	'833051'	,'TT');
insert into m_product_unused(code,type)values(	'833052'	,'TT');
insert into m_product_unused(code,type)values(	'833053'	,'TT');
insert into m_product_unused(code,type)values(	'833054'	,'TT');
insert into m_product_unused(code,type)values(	'833055'	,'TT');
insert into m_product_unused(code,type)values(	'833056'	,'TT');
insert into m_product_unused(code,type)values(	'833057'	,'TT');
insert into m_product_unused(code,type)values(	'833058'	,'TT');
insert into m_product_unused(code,type)values(	'833059'	,'TT');
insert into m_product_unused(code,type)values(	'833060'	,'TT');
insert into m_product_unused(code,type)values(	'833061'	,'TT');
insert into m_product_unused(code,type)values(	'833062'	,'TT');
insert into m_product_unused(code,type)values(	'833063'	,'TT');
insert into m_product_unused(code,type)values(	'833064'	,'TT');
insert into m_product_unused(code,type)values(	'833065'	,'TT');
insert into m_product_unused(code,type)values(	'833066'	,'TT');
insert into m_product_unused(code,type)values(	'833067'	,'TT');
insert into m_product_unused(code,type)values(	'833068'	,'TT');
insert into m_product_unused(code,type)values(	'833069'	,'TT');
insert into m_product_unused(code,type)values(	'833070'	,'TT');
insert into m_product_unused(code,type)values(	'833071'	,'TT');
insert into m_product_unused(code,type)values(	'833072'	,'TT');
insert into m_product_unused(code,type)values(	'833073'	,'TT');
insert into m_product_unused(code,type)values(	'833074'	,'TT');
insert into m_product_unused(code,type)values(	'833075'	,'TT');
insert into m_product_unused(code,type)values(	'833076'	,'TT');
insert into m_product_unused(code,type)values(	'833077'	,'TT');
insert into m_product_unused(code,type)values(	'833078'	,'TT');
insert into m_product_unused(code,type)values(	'833079'	,'TT');
insert into m_product_unused(code,type)values(	'823007'	,'TT');
insert into m_product_unused(code,type)values(	'823008'	,'TT');
insert into m_product_unused(code,type)values(	'823009'	,'TT');
insert into m_product_unused(code,type)values(	'823010'	,'TT');
insert into m_product_unused(code,type)values(	'823011'	,'TT');
insert into m_product_unused(code,type)values(	'823012'	,'TT');
insert into m_product_unused(code,type)values(	'823013'	,'TT');
insert into m_product_unused(code,type)values(	'823014'	,'TT');
insert into m_product_unused(code,type)values(	'823015'	,'TT');
insert into m_product_unused(code,type)values(	'823016'	,'TT');
insert into m_product_unused(code,type)values(	'823017'	,'TT');
insert into m_product_unused(code,type)values(	'823018'	,'TT');
insert into m_product_unused(code,type)values(	'823019'	,'TT');
insert into m_product_unused(code,type)values(	'823020'	,'TT');
insert into m_product_unused(code,type)values(	'823021'	,'TT');
insert into m_product_unused(code,type)values(	'823022'	,'TT');
insert into m_product_unused(code,type)values(	'823023'	,'TT');
insert into m_product_unused(code,type)values(	'823024'	,'TT');
insert into m_product_unused(code,type)values(	'823025'	,'TT');
insert into m_product_unused(code,type)values(	'823026'	,'TT');
insert into m_product_unused(code,type)values(	'823027'	,'TT');
insert into m_product_unused(code,type)values(	'823028'	,'TT');
insert into m_product_unused(code,type)values(	'823029'	,'TT');
insert into m_product_unused(code,type)values(	'823030'	,'TT');
insert into m_product_unused(code,type)values(	'823031'	,'TT');
insert into m_product_unused(code,type)values(	'823032'	,'TT');
insert into m_product_unused(code,type)values(	'823033'	,'TT');
insert into m_product_unused(code,type)values(	'823034'	,'TT');
insert into m_product_unused(code,type)values(	'823035'	,'TT');
insert into m_product_unused(code,type)values(	'823036'	,'TT');
insert into m_product_unused(code,type)values(	'823037'	,'TT');
insert into m_product_unused(code,type)values(	'823038'	,'TT');
insert into m_product_unused(code,type)values(	'823039'	,'TT');
insert into m_product_unused(code,type)values(	'823040'	,'TT');
insert into m_product_unused(code,type)values(	'823041'	,'TT');
insert into m_product_unused(code,type)values(	'823042'	,'TT');
insert into m_product_unused(code,type)values(	'823043'	,'TT');
insert into m_product_unused(code,type)values(	'823044'	,'TT');
insert into m_product_unused(code,type)values(	'823045'	,'TT');
insert into m_product_unused(code,type)values(	'823046'	,'TT');
insert into m_product_unused(code,type)values(	'823047'	,'TT');
insert into m_product_unused(code,type)values(	'823048'	,'TT');
insert into m_product_unused(code,type)values(	'824013'	,'TT');
insert into m_product_unused(code,type)values(	'824014'	,'TT');
insert into m_product_unused(code,type)values(	'824015'	,'TT');
insert into m_product_unused(code,type)values(	'824016'	,'TT');
insert into m_product_unused(code,type)values(	'824017'	,'TT');
insert into m_product_unused(code,type)values(	'824018'	,'TT');
insert into m_product_unused(code,type)values(	'824019'	,'TT');
insert into m_product_unused(code,type)values(	'824020'	,'TT');
insert into m_product_unused(code,type)values(	'824021'	,'TT');
insert into m_product_unused(code,type)values(	'824022'	,'TT');
insert into m_product_unused(code,type)values(	'824023'	,'TT');
insert into m_product_unused(code,type)values(	'824024'	,'TT');
insert into m_product_unused(code,type)values(	'824025'	,'TT');
insert into m_product_unused(code,type)values(	'824026'	,'TT');
insert into m_product_unused(code,type)values(	'824027'	,'TT');
insert into m_product_unused(code,type)values(	'824028'	,'TT');
insert into m_product_unused(code,type)values(	'824029'	,'TT');
insert into m_product_unused(code,type)values(	'824030'	,'TT');
insert into m_product_unused(code,type)values(	'824031'	,'TT');
insert into m_product_unused(code,type)values(	'824032'	,'TT');
insert into m_product_unused(code,type)values(	'824033'	,'TT');
insert into m_product_unused(code,type)values(	'826009'	,'TT');
insert into m_product_unused(code,type)values(	'826010'	,'TT');
insert into m_product_unused(code,type)values(	'826011'	,'TT');
insert into m_product_unused(code,type)values(	'826012'	,'TT');
insert into m_product_unused(code,type)values(	'826013'	,'TT');
insert into m_product_unused(code,type)values(	'826014'	,'TT');
insert into m_product_unused(code,type)values(	'826015'	,'TT');
insert into m_product_unused(code,type)values(	'826016'	,'TT');
insert into m_product_unused(code,type)values(	'826017'	,'TT');
insert into m_product_unused(code,type)values(	'826018'	,'TT');
insert into m_product_unused(code,type)values(	'826019'	,'TT');
insert into m_product_unused(code,type)values(	'826020'	,'TT');
insert into m_product_unused(code,type)values(	'827029'	,'TT');
insert into m_product_unused(code,type)values(	'827030'	,'TT');
insert into m_product_unused(code,type)values(	'827031'	,'TT');
insert into m_product_unused(code,type)values(	'827032'	,'TT');
insert into m_product_unused(code,type)values(	'827033'	,'TT');
insert into m_product_unused(code,type)values(	'827034'	,'TT');
insert into m_product_unused(code,type)values(	'827035'	,'TT');
insert into m_product_unused(code,type)values(	'827036'	,'TT');
insert into m_product_unused(code,type)values(	'827037'	,'TT');
insert into m_product_unused(code,type)values(	'827038'	,'TT');
insert into m_product_unused(code,type)values(	'827039'	,'TT');
insert into m_product_unused(code,type)values(	'827040'	,'TT');
insert into m_product_unused(code,type)values(	'833019'	,'TT');
insert into m_product_unused(code,type)values(	'833020'	,'TT');
insert into m_product_unused(code,type)values(	'833021'	,'TT');
insert into m_product_unused(code,type)values(	'833022'	,'TT');
insert into m_product_unused(code,type)values(	'833023'	,'TT');
insert into m_product_unused(code,type)values(	'833024'	,'TT');
insert into m_product_unused(code,type)values(	'833025'	,'TT');
insert into m_product_unused(code,type)values(	'833026'	,'TT');
insert into m_product_unused(code,type)values(	'833027'	,'TT');
insert into m_product_unused(code,type)values(	'833028'	,'TT');
insert into m_product_unused(code,type)values(	'833029'	,'TT');
insert into m_product_unused(code,type)values(	'833030'	,'TT');
insert into m_product_unused(code,type)values(	'833031'	,'TT');
insert into m_product_unused(code,type)values(	'836030'	,'TT');
insert into m_product_unused(code,type)values(	'836031'	,'TT');
insert into m_product_unused(code,type)values(	'836032'	,'TT');
insert into m_product_unused(code,type)values(	'836033'	,'TT');
insert into m_product_unused(code,type)values(	'836034'	,'TT');
insert into m_product_unused(code,type)values(	'836035'	,'TT');
insert into m_product_unused(code,type)values(	'836036'	,'TT');
insert into m_product_unused(code,type)values(	'836037'	,'TT');
insert into m_product_unused(code,type)values(	'836038'	,'TT');
insert into m_product_unused(code,type)values(	'836039'	,'TT');
insert into m_product_unused(code,type)values(	'836040'	,'TT');
insert into m_product_unused(code,type)values(	'836041'	,'TT');
insert into m_product_unused(code,type)values(	'836042'	,'TT');
insert into m_product_unused(code,type)values(	'836043'	,'TT');
insert into m_product_unused(code,type)values(	'836044'	,'TT');
insert into m_product_unused(code,type)values(	'836045'	,'TT');
insert into m_product_unused(code,type)values(	'836046'	,'TT');
insert into m_product_unused(code,type)values(	'836047'	,'TT');
insert into m_product_unused(code,type)values(	'836048'	,'TT');
insert into m_product_unused(code,type)values(	'836049'	,'TT');
insert into m_product_unused(code,type)values(	'836050'	,'TT');
insert into m_product_unused(code,type)values(	'836051'	,'TT');
insert into m_product_unused(code,type)values(	'836052'	,'TT');
insert into m_product_unused(code,type)values(	'836053'	,'TT');
insert into m_product_unused(code,type)values(	'836054'	,'TT');
insert into m_product_unused(code,type)values(	'836055'	,'TT');
insert into m_product_unused(code,type)values(	'837079'	,'TT');
insert into m_product_unused(code,type)values(	'837080'	,'TT');
insert into m_product_unused(code,type)values(	'837081'	,'TT');
insert into m_product_unused(code,type)values(	'837082'	,'TT');
insert into m_product_unused(code,type)values(	'837083'	,'TT');
insert into m_product_unused(code,type)values(	'837084'	,'TT');
insert into m_product_unused(code,type)values(	'837085'	,'TT');
insert into m_product_unused(code,type)values(	'837086'	,'TT');
insert into m_product_unused(code,type)values(	'837087'	,'TT');
insert into m_product_unused(code,type)values(	'837088'	,'TT');
insert into m_product_unused(code,type)values(	'837089'	,'TT');
insert into m_product_unused(code,type)values(	'837090'	,'TT');
insert into m_product_unused(code,type)values(	'837091'	,'TT');
insert into m_product_unused(code,type)values(	'837092'	,'TT');
insert into m_product_unused(code,type)values(	'837093'	,'TT');
insert into m_product_unused(code,type)values(	'837094'	,'TT');
insert into m_product_unused(code,type)values(	'837095'	,'TT');
insert into m_product_unused(code,type)values(	'837096'	,'TT');
insert into m_product_unused(code,type)values(	'837097'	,'TT');
insert into m_product_unused(code,type)values(	'837098'	,'TT');
insert into m_product_unused(code,type)values(	'837099'	,'TT');
insert into m_product_unused(code,type)values(	'837100'	,'TT');
insert into m_product_unused(code,type)values(	'837101'	,'TT');
insert into m_product_unused(code,type)values(	'833092'	,'TT');
insert into m_product_unused(code,type)values(	'833093'	,'TT');
insert into m_product_unused(code,type)values(	'833094'	,'TT');
insert into m_product_unused(code,type)values(	'833095'	,'TT');
insert into m_product_unused(code,type)values(	'833096'	,'TT');
insert into m_product_unused(code,type)values(	'833097'	,'TT');
insert into m_product_unused(code,type)values(	'833098'	,'TT');
insert into m_product_unused(code,type)values(	'833099'	,'TT');
insert into m_product_unused(code,type)values(	'833100'	,'TT');
insert into m_product_unused(code,type)values(	'833101'	,'TT');
insert into m_product_unused(code,type)values(	'833102'	,'TT');
insert into m_product_unused(code,type)values(	'833103'	,'TT');
insert into m_product_unused(code,type)values(	'833104'	,'TT');
insert into m_product_unused(code,type)values(	'833105'	,'TT');
insert into m_product_unused(code,type)values(	'833106'	,'TT');
insert into m_product_unused(code,type)values(	'833107'	,'TT');
insert into m_product_unused(code,type)values(	'833108'	,'TT');
insert into m_product_unused(code,type)values(	'833109'	,'TT');
insert into m_product_unused(code,type)values(	'833110'	,'TT');
insert into m_product_unused(code,type)values(	'833111'	,'TT');
insert into m_product_unused(code,type)values(	'833112'	,'TT');
insert into m_product_unused(code,type)values(	'833113'	,'TT');
insert into m_product_unused(code,type)values(	'833114'	,'TT');
insert into m_product_unused(code,type)values(	'833115'	,'TT');
insert into m_product_unused(code,type)values(	'833116'	,'TT');
insert into m_product_unused(code,type)values(	'833117'	,'TT');
insert into m_product_unused(code,type)values(	'833118'	,'TT');
insert into m_product_unused(code,type)values(	'833119'	,'TT');
insert into m_product_unused(code,type)values(	'833120'	,'TT');
insert into m_product_unused(code,type)values(	'833121'	,'TT');
insert into m_product_unused(code,type)values(	'833122'	,'TT');
insert into m_product_unused(code,type)values(	'833123'	,'TT');
insert into m_product_unused(code,type)values(	'833124'	,'TT');
insert into m_product_unused(code,type)values(	'833125'	,'TT');
insert into m_product_unused(code,type)values(	'833126'	,'TT');
insert into m_product_unused(code,type)values(	'833127'	,'TT');
insert into m_product_unused(code,type)values(	'833128'	,'TT');
insert into m_product_unused(code,type)values(	'833129'	,'TT');
insert into m_product_unused(code,type)values(	'833130'	,'TT');
insert into m_product_unused(code,type)values(	'833131'	,'TT');
insert into m_product_unused(code,type)values(	'833132'	,'TT');
insert into m_product_unused(code,type)values(	'833133'	,'TT');
insert into m_product_unused(code,type)values(	'833134'	,'TT');
insert into m_product_unused(code,type)values(	'833135'	,'TT');
insert into m_product_unused(code,type)values(	'833136'	,'TT');
insert into m_product_unused(code,type)values(	'833137'	,'TT');
insert into m_product_unused(code,type)values(	'833138'	,'TT');
insert into m_product_unused(code,type)values(	'833139'	,'TT');
insert into m_product_unused(code,type)values(	'833140'	,'TT');
insert into m_product_unused(code,type)values(	'833141'	,'TT');
insert into m_product_unused(code,type)values(	'833142'	,'TT');
insert into m_product_unused(code,type)values(	'833143'	,'TT');
insert into m_product_unused(code,type)values(	'833144'	,'TT');
insert into m_product_unused(code,type)values(	'833145'	,'TT');
insert into m_product_unused(code,type)values(	'833146'	,'TT');
insert into m_product_unused(code,type)values(	'833147'	,'TT');
insert into m_product_unused(code,type)values(	'833148'	,'TT');
insert into m_product_unused(code,type)values(	'833149'	,'TT');
insert into m_product_unused(code,type)values(	'833150'	,'TT');
insert into m_product_unused(code,type)values(	'833151'	,'TT');
insert into m_product_unused(code,type)values(	'833152'	,'TT');
insert into m_product_unused(code,type)values(	'833153'	,'TT');
insert into m_product_unused(code,type)values(	'834046'	,'TT');
insert into m_product_unused(code,type)values(	'834047'	,'TT');
insert into m_product_unused(code,type)values(	'834048'	,'TT');
insert into m_product_unused(code,type)values(	'834049'	,'TT');
insert into m_product_unused(code,type)values(	'834050'	,'TT');
insert into m_product_unused(code,type)values(	'834051'	,'TT');
insert into m_product_unused(code,type)values(	'834052'	,'TT');
insert into m_product_unused(code,type)values(	'834053'	,'TT');
insert into m_product_unused(code,type)values(	'834054'	,'TT');
insert into m_product_unused(code,type)values(	'834055'	,'TT');
insert into m_product_unused(code,type)values(	'834056'	,'TT');
insert into m_product_unused(code,type)values(	'834057'	,'TT');
insert into m_product_unused(code,type)values(	'834058'	,'TT');
insert into m_product_unused(code,type)values(	'834059'	,'TT');
insert into m_product_unused(code,type)values(	'834060'	,'TT');
insert into m_product_unused(code,type)values(	'834061'	,'TT');
insert into m_product_unused(code,type)values(	'834062'	,'TT');
insert into m_product_unused(code,type)values(	'834063'	,'TT');
insert into m_product_unused(code,type)values(	'834064'	,'TT');
insert into m_product_unused(code,type)values(	'834065'	,'TT');
insert into m_product_unused(code,type)values(	'834066'	,'TT');
insert into m_product_unused(code,type)values(	'834067'	,'TT');
insert into m_product_unused(code,type)values(	'834068'	,'TT');
insert into m_product_unused(code,type)values(	'834069'	,'TT');
insert into m_product_unused(code,type)values(	'834070'	,'TT');
insert into m_product_unused(code,type)values(	'834071'	,'TT');
insert into m_product_unused(code,type)values(	'834072'	,'TT');
insert into m_product_unused(code,type)values(	'834073'	,'TT');
insert into m_product_unused(code,type)values(	'834074'	,'TT');
insert into m_product_unused(code,type)values(	'834075'	,'TT');
insert into m_product_unused(code,type)values(	'834076'	,'TT');
insert into m_product_unused(code,type)values(	'834077'	,'TT');
insert into m_product_unused(code,type)values(	'834078'	,'TT');
insert into m_product_unused(code,type)values(	'834079'	,'TT');
insert into m_product_unused(code,type)values(	'834080'	,'TT');
insert into m_product_unused(code,type)values(	'834081'	,'TT');
insert into m_product_unused(code,type)values(	'834082'	,'TT');
insert into m_product_unused(code,type)values(	'834083'	,'TT');
insert into m_product_unused(code,type)values(	'834084'	,'TT');
insert into m_product_unused(code,type)values(	'834085'	,'TT');
insert into m_product_unused(code,type)values(	'834086'	,'TT');
insert into m_product_unused(code,type)values(	'834087'	,'TT');
insert into m_product_unused(code,type)values(	'834088'	,'TT');
insert into m_product_unused(code,type)values(	'834089'	,'TT');
insert into m_product_unused(code,type)values(	'834090'	,'TT');
insert into m_product_unused(code,type)values(	'834091'	,'TT');
insert into m_product_unused(code,type)values(	'834092'	,'TT');
insert into m_product_unused(code,type)values(	'834093'	,'TT');
insert into m_product_unused(code,type)values(	'834094'	,'TT');
insert into m_product_unused(code,type)values(	'834095'	,'TT');
insert into m_product_unused(code,type)values(	'834096'	,'TT');
insert into m_product_unused(code,type)values(	'834097'	,'TT');
insert into m_product_unused(code,type)values(	'834098'	,'TT');
insert into m_product_unused(code,type)values(	'834099'	,'TT');
insert into m_product_unused(code,type)values(	'834100'	,'TT');
insert into m_product_unused(code,type)values(	'834101'	,'TT');
insert into m_product_unused(code,type)values(	'834102'	,'TT');
insert into m_product_unused(code,type)values(	'834103'	,'TT');
insert into m_product_unused(code,type)values(	'834104'	,'TT');
insert into m_product_unused(code,type)values(	'834105'	,'TT');
insert into m_product_unused(code,type)values(	'834106'	,'TT');
insert into m_product_unused(code,type)values(	'834107'	,'TT');
insert into m_product_unused(code,type)values(	'834108'	,'TT');
insert into m_product_unused(code,type)values(	'836023'	,'TT');
insert into m_product_unused(code,type)values(	'836024'	,'TT');
insert into m_product_unused(code,type)values(	'836025'	,'TT');
insert into m_product_unused(code,type)values(	'836026'	,'TT');
insert into m_product_unused(code,type)values(	'836027'	,'TT');
insert into m_product_unused(code,type)values(	'836028'	,'TT');
insert into m_product_unused(code,type)values(	'836029'	,'TT');
insert into m_product_unused(code,type)values(	'837102'	,'TT');
insert into m_product_unused(code,type)values(	'837103'	,'TT');
insert into m_product_unused(code,type)values(	'837104'	,'TT');
insert into m_product_unused(code,type)values(	'837105'	,'TT');
insert into m_product_unused(code,type)values(	'837106'	,'TT');
insert into m_product_unused(code,type)values(	'837107'	,'TT');
insert into m_product_unused(code,type)values(	'837108'	,'TT');
insert into m_product_unused(code,type)values(	'837109'	,'TT');
insert into m_product_unused(code,type)values(	'837110'	,'TT');
insert into m_product_unused(code,type)values(	'837111'	,'TT');
insert into m_product_unused(code,type)values(	'837112'	,'TT');
insert into m_product_unused(code,type)values(	'837113'	,'TT');
insert into m_product_unused(code,type)values(	'837114'	,'TT');
insert into m_product_unused(code,type)values(	'837115'	,'TT');
insert into m_product_unused(code,type)values(	'837116'	,'TT');
insert into m_product_unused(code,type)values(	'837117'	,'TT');
insert into m_product_unused(code,type)values(	'837118'	,'TT');
insert into m_product_unused(code,type)values(	'837119'	,'TT');
insert into m_product_unused(code,type)values(	'837120'	,'TT');
insert into m_product_unused(code,type)values(	'837121'	,'TT');
insert into m_product_unused(code,type)values(	'837122'	,'TT');
insert into m_product_unused(code,type)values(	'837123'	,'TT');
insert into m_product_unused(code,type)values(	'837124'	,'TT');
insert into m_product_unused(code,type)values(	'837125'	,'TT');
insert into m_product_unused(code,type)values(	'837126'	,'TT');
insert into m_product_unused(code,type)values(	'837127'	,'TT');
insert into m_product_unused(code,type)values(	'837128'	,'TT');
insert into m_product_unused(code,type)values(	'837129'	,'TT');
insert into m_product_unused(code,type)values(	'837130'	,'TT');
insert into m_product_unused(code,type)values(	'837131'	,'TT');
insert into m_product_unused(code,type)values(	'837132'	,'TT');
insert into m_product_unused(code,type)values(	'823049'	,'TT');
insert into m_product_unused(code,type)values(	'823050'	,'TT');
insert into m_product_unused(code,type)values(	'823051'	,'TT');
insert into m_product_unused(code,type)values(	'823052'	,'TT');
insert into m_product_unused(code,type)values(	'823053'	,'TT');
insert into m_product_unused(code,type)values(	'823054'	,'TT');
insert into m_product_unused(code,type)values(	'824034'	,'TT');
insert into m_product_unused(code,type)values(	'824035'	,'TT');
insert into m_product_unused(code,type)values(	'824036'	,'TT');
insert into m_product_unused(code,type)values(	'824037'	,'TT');
insert into m_product_unused(code,type)values(	'824038'	,'TT');
insert into m_product_unused(code,type)values(	'824039'	,'TT');
insert into m_product_unused(code,type)values(	'824040'	,'TT');
insert into m_product_unused(code,type)values(	'824041'	,'TT');
insert into m_product_unused(code,type)values(	'824042'	,'TT');
insert into m_product_unused(code,type)values(	'824043'	,'TT');
insert into m_product_unused(code,type)values(	'824044'	,'TT');
insert into m_product_unused(code,type)values(	'824045'	,'TT');
insert into m_product_unused(code,type)values(	'824046'	,'TT');
insert into m_product_unused(code,type)values(	'824047'	,'TT');
insert into m_product_unused(code,type)values(	'824048'	,'TT');
insert into m_product_unused(code,type)values(	'824049'	,'TT');
insert into m_product_unused(code,type)values(	'824050'	,'TT');
insert into m_product_unused(code,type)values(	'824051'	,'TT');
insert into m_product_unused(code,type)values(	'833154'	,'TT');
insert into m_product_unused(code,type)values(	'833155'	,'TT');
insert into m_product_unused(code,type)values(	'833156'	,'TT');
insert into m_product_unused(code,type)values(	'833157'	,'TT');
insert into m_product_unused(code,type)values(	'833158'	,'TT');
insert into m_product_unused(code,type)values(	'833159'	,'TT');
insert into m_product_unused(code,type)values(	'833160'	,'TT');
insert into m_product_unused(code,type)values(	'833161'	,'TT');
insert into m_product_unused(code,type)values(	'833162'	,'TT');
insert into m_product_unused(code,type)values(	'833163'	,'TT');
insert into m_product_unused(code,type)values(	'833164'	,'TT');
insert into m_product_unused(code,type)values(	'833165'	,'TT');
insert into m_product_unused(code,type)values(	'833166'	,'TT');
insert into m_product_unused(code,type)values(	'833167'	,'TT');
insert into m_product_unused(code,type)values(	'833168'	,'TT');
insert into m_product_unused(code,type)values(	'833169'	,'TT');
insert into m_product_unused(code,type)values(	'833170'	,'TT');
insert into m_product_unused(code,type)values(	'833171'	,'TT');
insert into m_product_unused(code,type)values(	'834109'	,'TT');
insert into m_product_unused(code,type)values(	'834110'	,'TT');
insert into m_product_unused(code,type)values(	'834111'	,'TT');
insert into m_product_unused(code,type)values(	'834112'	,'TT');
insert into m_product_unused(code,type)values(	'834113'	,'TT');
insert into m_product_unused(code,type)values(	'834114'	,'TT');
insert into m_product_unused(code,type)values(	'834115'	,'TT');
insert into m_product_unused(code,type)values(	'834116'	,'TT');
insert into m_product_unused(code,type)values(	'834117'	,'TT');
insert into m_product_unused(code,type)values(	'834118'	,'TT');
insert into m_product_unused(code,type)values(	'834119'	,'TT');
insert into m_product_unused(code,type)values(	'834120'	,'TT');
insert into m_product_unused(code,type)values(	'834121'	,'TT');
insert into m_product_unused(code,type)values(	'834122'	,'TT');
insert into m_product_unused(code,type)values(	'834123'	,'TT');
insert into m_product_unused(code,type)values(	'834124'	,'TT');
insert into m_product_unused(code,type)values(	'834125'	,'TT');
insert into m_product_unused(code,type)values(	'834126'	,'TT');
insert into m_product_unused(code,type)values(	'834127'	,'TT');
insert into m_product_unused(code,type)values(	'834128'	,'TT');
insert into m_product_unused(code,type)values(	'834129'	,'TT');
insert into m_product_unused(code,type)values(	'834130'	,'TT');
insert into m_product_unused(code,type)values(	'834131'	,'TT');
insert into m_product_unused(code,type)values(	'834132'	,'TT');
insert into m_product_unused(code,type)values(	'834133'	,'TT');
insert into m_product_unused(code,type)values(	'834134'	,'TT');
insert into m_product_unused(code,type)values(	'834135'	,'TT');
insert into m_product_unused(code,type)values(	'834136'	,'TT');
insert into m_product_unused(code,type)values(	'834137'	,'TT');
insert into m_product_unused(code,type)values(	'834138'	,'TT');
insert into m_product_unused(code,type)values(	'834139'	,'TT');
insert into m_product_unused(code,type)values(	'834140'	,'TT');
insert into m_product_unused(code,type)values(	'834141'	,'TT');
insert into m_product_unused(code,type)values(	'834142'	,'TT');
insert into m_product_unused(code,type)values(	'834143'	,'TT');
insert into m_product_unused(code,type)values(	'834144'	,'TT');
insert into m_product_unused(code,type)values(	'834145'	,'TT');
insert into m_product_unused(code,type)values(	'834146'	,'TT');
insert into m_product_unused(code,type)values(	'834147'	,'TT');
insert into m_product_unused(code,type)values(	'834148'	,'TT');
insert into m_product_unused(code,type)values(	'834149'	,'TT');
insert into m_product_unused(code,type)values(	'834150'	,'TT');
insert into m_product_unused(code,type)values(	'834151'	,'TT');
insert into m_product_unused(code,type)values(	'834152'	,'TT');
insert into m_product_unused(code,type)values(	'834153'	,'TT');
insert into m_product_unused(code,type)values(	'834154'	,'TT');
insert into m_product_unused(code,type)values(	'834155'	,'TT');
insert into m_product_unused(code,type)values(	'834156'	,'TT');
insert into m_product_unused(code,type)values(	'834157'	,'TT');
insert into m_product_unused(code,type)values(	'834158'	,'TT');
insert into m_product_unused(code,type)values(	'834159'	,'TT');
insert into m_product_unused(code,type)values(	'834160'	,'TT');
insert into m_product_unused(code,type)values(	'834161'	,'TT');
insert into m_product_unused(code,type)values(	'834162'	,'TT');
insert into m_product_unused(code,type)values(	'834163'	,'TT');
insert into m_product_unused(code,type)values(	'834164'	,'TT');
insert into m_product_unused(code,type)values(	'834165'	,'TT');
insert into m_product_unused(code,type)values(	'834166'	,'TT');
insert into m_product_unused(code,type)values(	'834167'	,'TT');
insert into m_product_unused(code,type)values(	'834168'	,'TT');
insert into m_product_unused(code,type)values(	'834169'	,'TT');
insert into m_product_unused(code,type)values(	'834170'	,'TT');
insert into m_product_unused(code,type)values(	'834171'	,'TT');

/** product unused van **/
insert into m_product_unused(code,type)values(	'822013'	,'VAN');
insert into m_product_unused(code,type)values(	'822014'	,'VAN');
insert into m_product_unused(code,type)values(	'822015'	,'VAN');
insert into m_product_unused(code,type)values(	'822016'	,'VAN');
insert into m_product_unused(code,type)values(	'822017'	,'VAN');
insert into m_product_unused(code,type)values(	'822018'	,'VAN');
insert into m_product_unused(code,type)values(	'822019'	,'VAN');
insert into m_product_unused(code,type)values(	'822020'	,'VAN');
insert into m_product_unused(code,type)values(	'823001'	,'VAN');
insert into m_product_unused(code,type)values(	'823002'	,'VAN');
insert into m_product_unused(code,type)values(	'823003'	,'VAN');
insert into m_product_unused(code,type)values(	'823004'	,'VAN');
insert into m_product_unused(code,type)values(	'823005'	,'VAN');
insert into m_product_unused(code,type)values(	'823006'	,'VAN');
insert into m_product_unused(code,type)values(	'824001'	,'VAN');
insert into m_product_unused(code,type)values(	'824002'	,'VAN');
insert into m_product_unused(code,type)values(	'824003'	,'VAN');
insert into m_product_unused(code,type)values(	'824004'	,'VAN');
insert into m_product_unused(code,type)values(	'824005'	,'VAN');
insert into m_product_unused(code,type)values(	'824006'	,'VAN');
insert into m_product_unused(code,type)values(	'824007'	,'VAN');
insert into m_product_unused(code,type)values(	'824008'	,'VAN');
insert into m_product_unused(code,type)values(	'824009'	,'VAN');
insert into m_product_unused(code,type)values(	'824010'	,'VAN');
insert into m_product_unused(code,type)values(	'824011'	,'VAN');
insert into m_product_unused(code,type)values(	'824012'	,'VAN');
insert into m_product_unused(code,type)values(	'825001'	,'VAN');
insert into m_product_unused(code,type)values(	'825002'	,'VAN');
insert into m_product_unused(code,type)values(	'825003'	,'VAN');
insert into m_product_unused(code,type)values(	'825004'	,'VAN');
insert into m_product_unused(code,type)values(	'825005'	,'VAN');
insert into m_product_unused(code,type)values(	'825006'	,'VAN');
insert into m_product_unused(code,type)values(	'825007'	,'VAN');
insert into m_product_unused(code,type)values(	'825008'	,'VAN');
insert into m_product_unused(code,type)values(	'825009'	,'VAN');
insert into m_product_unused(code,type)values(	'825010'	,'VAN');
insert into m_product_unused(code,type)values(	'825011'	,'VAN');
insert into m_product_unused(code,type)values(	'825012'	,'VAN');
insert into m_product_unused(code,type)values(	'825013'	,'VAN');
insert into m_product_unused(code,type)values(	'825014'	,'VAN');
insert into m_product_unused(code,type)values(	'825015'	,'VAN');
insert into m_product_unused(code,type)values(	'825016'	,'VAN');
insert into m_product_unused(code,type)values(	'825017'	,'VAN');
insert into m_product_unused(code,type)values(	'825018'	,'VAN');
insert into m_product_unused(code,type)values(	'825019'	,'VAN');
insert into m_product_unused(code,type)values(	'825020'	,'VAN');
insert into m_product_unused(code,type)values(	'825021'	,'VAN');
insert into m_product_unused(code,type)values(	'825022'	,'VAN');
insert into m_product_unused(code,type)values(	'825023'	,'VAN');
insert into m_product_unused(code,type)values(	'825024'	,'VAN');
insert into m_product_unused(code,type)values(	'826001'	,'VAN');
insert into m_product_unused(code,type)values(	'826002'	,'VAN');
insert into m_product_unused(code,type)values(	'826003'	,'VAN');
insert into m_product_unused(code,type)values(	'826004'	,'VAN');
insert into m_product_unused(code,type)values(	'826005'	,'VAN');
insert into m_product_unused(code,type)values(	'826006'	,'VAN');
insert into m_product_unused(code,type)values(	'826007'	,'VAN');
insert into m_product_unused(code,type)values(	'826008'	,'VAN');
insert into m_product_unused(code,type)values(	'827001'	,'VAN');
insert into m_product_unused(code,type)values(	'827002'	,'VAN');
insert into m_product_unused(code,type)values(	'827003'	,'VAN');
insert into m_product_unused(code,type)values(	'827004'	,'VAN');
insert into m_product_unused(code,type)values(	'827005'	,'VAN');
insert into m_product_unused(code,type)values(	'827006'	,'VAN');
insert into m_product_unused(code,type)values(	'827007'	,'VAN');
insert into m_product_unused(code,type)values(	'827008'	,'VAN');
insert into m_product_unused(code,type)values(	'827009'	,'VAN');
insert into m_product_unused(code,type)values(	'827010'	,'VAN');
insert into m_product_unused(code,type)values(	'827011'	,'VAN');
insert into m_product_unused(code,type)values(	'827012'	,'VAN');
insert into m_product_unused(code,type)values(	'827013'	,'VAN');
insert into m_product_unused(code,type)values(	'827014'	,'VAN');
insert into m_product_unused(code,type)values(	'827015'	,'VAN');
insert into m_product_unused(code,type)values(	'827016'	,'VAN');
insert into m_product_unused(code,type)values(	'827017'	,'VAN');
insert into m_product_unused(code,type)values(	'827018'	,'VAN');
insert into m_product_unused(code,type)values(	'827019'	,'VAN');
insert into m_product_unused(code,type)values(	'827020'	,'VAN');
insert into m_product_unused(code,type)values(	'827021'	,'VAN');
insert into m_product_unused(code,type)values(	'827022'	,'VAN');
insert into m_product_unused(code,type)values(	'827023'	,'VAN');
insert into m_product_unused(code,type)values(	'827024'	,'VAN');
insert into m_product_unused(code,type)values(	'827025'	,'VAN');
insert into m_product_unused(code,type)values(	'827026'	,'VAN');
insert into m_product_unused(code,type)values(	'827027'	,'VAN');
insert into m_product_unused(code,type)values(	'827028'	,'VAN');
insert into m_product_unused(code,type)values(	'828001'	,'VAN');
insert into m_product_unused(code,type)values(	'828002'	,'VAN');
insert into m_product_unused(code,type)values(	'828003'	,'VAN');
insert into m_product_unused(code,type)values(	'828004'	,'VAN');
insert into m_product_unused(code,type)values(	'828005'	,'VAN');
insert into m_product_unused(code,type)values(	'828006'	,'VAN');
insert into m_product_unused(code,type)values(	'822001'	,'VAN');
insert into m_product_unused(code,type)values(	'822002'	,'VAN');
insert into m_product_unused(code,type)values(	'822003'	,'VAN');
insert into m_product_unused(code,type)values(	'822004'	,'VAN');
insert into m_product_unused(code,type)values(	'822005'	,'VAN');
insert into m_product_unused(code,type)values(	'822006'	,'VAN');
insert into m_product_unused(code,type)values(	'822007'	,'VAN');
insert into m_product_unused(code,type)values(	'822008'	,'VAN');
insert into m_product_unused(code,type)values(	'822009'	,'VAN');
insert into m_product_unused(code,type)values(	'822010'	,'VAN');
insert into m_product_unused(code,type)values(	'822011'	,'VAN');
insert into m_product_unused(code,type)values(	'822012'	,'VAN');
insert into m_product_unused(code,type)values(	'821001'	,'VAN');
insert into m_product_unused(code,type)values(	'833032'	,'VAN');
insert into m_product_unused(code,type)values(	'833033'	,'VAN');
insert into m_product_unused(code,type)values(	'833034'	,'VAN');
insert into m_product_unused(code,type)values(	'833035'	,'VAN');
insert into m_product_unused(code,type)values(	'833036'	,'VAN');
insert into m_product_unused(code,type)values(	'833037'	,'VAN');
insert into m_product_unused(code,type)values(	'833038'	,'VAN');
insert into m_product_unused(code,type)values(	'833039'	,'VAN');
insert into m_product_unused(code,type)values(	'833040'	,'VAN');
insert into m_product_unused(code,type)values(	'833041'	,'VAN');
insert into m_product_unused(code,type)values(	'833042'	,'VAN');
insert into m_product_unused(code,type)values(	'833043'	,'VAN');
insert into m_product_unused(code,type)values(	'833080'	,'VAN');
insert into m_product_unused(code,type)values(	'833081'	,'VAN');
insert into m_product_unused(code,type)values(	'833082'	,'VAN');
insert into m_product_unused(code,type)values(	'833083'	,'VAN');
insert into m_product_unused(code,type)values(	'833084'	,'VAN');
insert into m_product_unused(code,type)values(	'833085'	,'VAN');
insert into m_product_unused(code,type)values(	'833086'	,'VAN');
insert into m_product_unused(code,type)values(	'833087'	,'VAN');
insert into m_product_unused(code,type)values(	'833088'	,'VAN');
insert into m_product_unused(code,type)values(	'833089'	,'VAN');
insert into m_product_unused(code,type)values(	'833090'	,'VAN');
insert into m_product_unused(code,type)values(	'833091'	,'VAN');
insert into m_product_unused(code,type)values(	'833044'	,'VAN');
insert into m_product_unused(code,type)values(	'833045'	,'VAN');
insert into m_product_unused(code,type)values(	'833046'	,'VAN');
insert into m_product_unused(code,type)values(	'833047'	,'VAN');
insert into m_product_unused(code,type)values(	'833048'	,'VAN');
insert into m_product_unused(code,type)values(	'833049'	,'VAN');
insert into m_product_unused(code,type)values(	'833050'	,'VAN');
insert into m_product_unused(code,type)values(	'833051'	,'VAN');
insert into m_product_unused(code,type)values(	'833052'	,'VAN');
insert into m_product_unused(code,type)values(	'833053'	,'VAN');
insert into m_product_unused(code,type)values(	'833054'	,'VAN');
insert into m_product_unused(code,type)values(	'833055'	,'VAN');
insert into m_product_unused(code,type)values(	'833056'	,'VAN');
insert into m_product_unused(code,type)values(	'833057'	,'VAN');
insert into m_product_unused(code,type)values(	'833058'	,'VAN');
insert into m_product_unused(code,type)values(	'833059'	,'VAN');
insert into m_product_unused(code,type)values(	'833060'	,'VAN');
insert into m_product_unused(code,type)values(	'833061'	,'VAN');
insert into m_product_unused(code,type)values(	'833062'	,'VAN');
insert into m_product_unused(code,type)values(	'833063'	,'VAN');
insert into m_product_unused(code,type)values(	'833064'	,'VAN');
insert into m_product_unused(code,type)values(	'833065'	,'VAN');
insert into m_product_unused(code,type)values(	'833066'	,'VAN');
insert into m_product_unused(code,type)values(	'833067'	,'VAN');
insert into m_product_unused(code,type)values(	'833068'	,'VAN');
insert into m_product_unused(code,type)values(	'833069'	,'VAN');
insert into m_product_unused(code,type)values(	'833070'	,'VAN');
insert into m_product_unused(code,type)values(	'833071'	,'VAN');
insert into m_product_unused(code,type)values(	'833072'	,'VAN');
insert into m_product_unused(code,type)values(	'833073'	,'VAN');
insert into m_product_unused(code,type)values(	'833074'	,'VAN');
insert into m_product_unused(code,type)values(	'833075'	,'VAN');
insert into m_product_unused(code,type)values(	'833076'	,'VAN');
insert into m_product_unused(code,type)values(	'833077'	,'VAN');
insert into m_product_unused(code,type)values(	'833078'	,'VAN');
insert into m_product_unused(code,type)values(	'833079'	,'VAN');
insert into m_product_unused(code,type)values(	'823007'	,'VAN');
insert into m_product_unused(code,type)values(	'823008'	,'VAN');
insert into m_product_unused(code,type)values(	'823009'	,'VAN');
insert into m_product_unused(code,type)values(	'823010'	,'VAN');
insert into m_product_unused(code,type)values(	'823011'	,'VAN');
insert into m_product_unused(code,type)values(	'823012'	,'VAN');
insert into m_product_unused(code,type)values(	'823013'	,'VAN');
insert into m_product_unused(code,type)values(	'823014'	,'VAN');
insert into m_product_unused(code,type)values(	'823015'	,'VAN');
insert into m_product_unused(code,type)values(	'823016'	,'VAN');
insert into m_product_unused(code,type)values(	'823017'	,'VAN');
insert into m_product_unused(code,type)values(	'823018'	,'VAN');
insert into m_product_unused(code,type)values(	'823019'	,'VAN');
insert into m_product_unused(code,type)values(	'823020'	,'VAN');
insert into m_product_unused(code,type)values(	'823021'	,'VAN');
insert into m_product_unused(code,type)values(	'823022'	,'VAN');
insert into m_product_unused(code,type)values(	'823023'	,'VAN');
insert into m_product_unused(code,type)values(	'823024'	,'VAN');
insert into m_product_unused(code,type)values(	'823025'	,'VAN');
insert into m_product_unused(code,type)values(	'823026'	,'VAN');
insert into m_product_unused(code,type)values(	'823027'	,'VAN');
insert into m_product_unused(code,type)values(	'823028'	,'VAN');
insert into m_product_unused(code,type)values(	'823029'	,'VAN');
insert into m_product_unused(code,type)values(	'823030'	,'VAN');
insert into m_product_unused(code,type)values(	'823031'	,'VAN');
insert into m_product_unused(code,type)values(	'823032'	,'VAN');
insert into m_product_unused(code,type)values(	'823033'	,'VAN');
insert into m_product_unused(code,type)values(	'823034'	,'VAN');
insert into m_product_unused(code,type)values(	'823035'	,'VAN');
insert into m_product_unused(code,type)values(	'823036'	,'VAN');
insert into m_product_unused(code,type)values(	'823037'	,'VAN');
insert into m_product_unused(code,type)values(	'823038'	,'VAN');
insert into m_product_unused(code,type)values(	'823039'	,'VAN');
insert into m_product_unused(code,type)values(	'823040'	,'VAN');
insert into m_product_unused(code,type)values(	'823041'	,'VAN');
insert into m_product_unused(code,type)values(	'823042'	,'VAN');
insert into m_product_unused(code,type)values(	'823043'	,'VAN');
insert into m_product_unused(code,type)values(	'823044'	,'VAN');
insert into m_product_unused(code,type)values(	'823045'	,'VAN');
insert into m_product_unused(code,type)values(	'823046'	,'VAN');
insert into m_product_unused(code,type)values(	'823047'	,'VAN');
insert into m_product_unused(code,type)values(	'823048'	,'VAN');
insert into m_product_unused(code,type)values(	'824013'	,'VAN');
insert into m_product_unused(code,type)values(	'824014'	,'VAN');
insert into m_product_unused(code,type)values(	'824015'	,'VAN');
insert into m_product_unused(code,type)values(	'824016'	,'VAN');
insert into m_product_unused(code,type)values(	'824017'	,'VAN');
insert into m_product_unused(code,type)values(	'824018'	,'VAN');
insert into m_product_unused(code,type)values(	'824019'	,'VAN');
insert into m_product_unused(code,type)values(	'824020'	,'VAN');
insert into m_product_unused(code,type)values(	'824021'	,'VAN');
insert into m_product_unused(code,type)values(	'824022'	,'VAN');
insert into m_product_unused(code,type)values(	'824023'	,'VAN');
insert into m_product_unused(code,type)values(	'824024'	,'VAN');
insert into m_product_unused(code,type)values(	'824025'	,'VAN');
insert into m_product_unused(code,type)values(	'824026'	,'VAN');
insert into m_product_unused(code,type)values(	'824027'	,'VAN');
insert into m_product_unused(code,type)values(	'824028'	,'VAN');
insert into m_product_unused(code,type)values(	'824029'	,'VAN');
insert into m_product_unused(code,type)values(	'824030'	,'VAN');
insert into m_product_unused(code,type)values(	'824031'	,'VAN');
insert into m_product_unused(code,type)values(	'824032'	,'VAN');
insert into m_product_unused(code,type)values(	'824033'	,'VAN');
insert into m_product_unused(code,type)values(	'826009'	,'VAN');
insert into m_product_unused(code,type)values(	'826010'	,'VAN');
insert into m_product_unused(code,type)values(	'826011'	,'VAN');
insert into m_product_unused(code,type)values(	'826012'	,'VAN');
insert into m_product_unused(code,type)values(	'826013'	,'VAN');
insert into m_product_unused(code,type)values(	'826014'	,'VAN');
insert into m_product_unused(code,type)values(	'826015'	,'VAN');
insert into m_product_unused(code,type)values(	'826016'	,'VAN');
insert into m_product_unused(code,type)values(	'826017'	,'VAN');
insert into m_product_unused(code,type)values(	'826018'	,'VAN');
insert into m_product_unused(code,type)values(	'826019'	,'VAN');
insert into m_product_unused(code,type)values(	'826020'	,'VAN');
insert into m_product_unused(code,type)values(	'827029'	,'VAN');
insert into m_product_unused(code,type)values(	'827030'	,'VAN');
insert into m_product_unused(code,type)values(	'827031'	,'VAN');
insert into m_product_unused(code,type)values(	'827032'	,'VAN');
insert into m_product_unused(code,type)values(	'827033'	,'VAN');
insert into m_product_unused(code,type)values(	'827034'	,'VAN');
insert into m_product_unused(code,type)values(	'827035'	,'VAN');
insert into m_product_unused(code,type)values(	'827036'	,'VAN');
insert into m_product_unused(code,type)values(	'827037'	,'VAN');
insert into m_product_unused(code,type)values(	'827038'	,'VAN');
insert into m_product_unused(code,type)values(	'827039'	,'VAN');
insert into m_product_unused(code,type)values(	'827040'	,'VAN');
insert into m_product_unused(code,type)values(	'833019'	,'VAN');
insert into m_product_unused(code,type)values(	'833020'	,'VAN');
insert into m_product_unused(code,type)values(	'833021'	,'VAN');
insert into m_product_unused(code,type)values(	'833022'	,'VAN');
insert into m_product_unused(code,type)values(	'833023'	,'VAN');
insert into m_product_unused(code,type)values(	'833024'	,'VAN');
insert into m_product_unused(code,type)values(	'833025'	,'VAN');
insert into m_product_unused(code,type)values(	'833026'	,'VAN');
insert into m_product_unused(code,type)values(	'833027'	,'VAN');
insert into m_product_unused(code,type)values(	'833028'	,'VAN');
insert into m_product_unused(code,type)values(	'833029'	,'VAN');
insert into m_product_unused(code,type)values(	'833030'	,'VAN');
insert into m_product_unused(code,type)values(	'833031'	,'VAN');
insert into m_product_unused(code,type)values(	'836030'	,'VAN');
insert into m_product_unused(code,type)values(	'836031'	,'VAN');
insert into m_product_unused(code,type)values(	'836032'	,'VAN');
insert into m_product_unused(code,type)values(	'836033'	,'VAN');
insert into m_product_unused(code,type)values(	'836034'	,'VAN');
insert into m_product_unused(code,type)values(	'836035'	,'VAN');
insert into m_product_unused(code,type)values(	'836036'	,'VAN');
insert into m_product_unused(code,type)values(	'836037'	,'VAN');
insert into m_product_unused(code,type)values(	'836038'	,'VAN');
insert into m_product_unused(code,type)values(	'836039'	,'VAN');
insert into m_product_unused(code,type)values(	'836040'	,'VAN');
insert into m_product_unused(code,type)values(	'836041'	,'VAN');
insert into m_product_unused(code,type)values(	'836042'	,'VAN');
insert into m_product_unused(code,type)values(	'836043'	,'VAN');
insert into m_product_unused(code,type)values(	'836044'	,'VAN');
insert into m_product_unused(code,type)values(	'836045'	,'VAN');
insert into m_product_unused(code,type)values(	'836046'	,'VAN');
insert into m_product_unused(code,type)values(	'836047'	,'VAN');
insert into m_product_unused(code,type)values(	'836048'	,'VAN');
insert into m_product_unused(code,type)values(	'836049'	,'VAN');
insert into m_product_unused(code,type)values(	'836050'	,'VAN');
insert into m_product_unused(code,type)values(	'836051'	,'VAN');
insert into m_product_unused(code,type)values(	'836052'	,'VAN');
insert into m_product_unused(code,type)values(	'836053'	,'VAN');
insert into m_product_unused(code,type)values(	'836054'	,'VAN');
insert into m_product_unused(code,type)values(	'836055'	,'VAN');
insert into m_product_unused(code,type)values(	'837079'	,'VAN');
insert into m_product_unused(code,type)values(	'837080'	,'VAN');
insert into m_product_unused(code,type)values(	'837081'	,'VAN');
insert into m_product_unused(code,type)values(	'837082'	,'VAN');
insert into m_product_unused(code,type)values(	'837083'	,'VAN');
insert into m_product_unused(code,type)values(	'837084'	,'VAN');
insert into m_product_unused(code,type)values(	'837085'	,'VAN');
insert into m_product_unused(code,type)values(	'837086'	,'VAN');
insert into m_product_unused(code,type)values(	'837087'	,'VAN');
insert into m_product_unused(code,type)values(	'837088'	,'VAN');
insert into m_product_unused(code,type)values(	'837089'	,'VAN');
insert into m_product_unused(code,type)values(	'837090'	,'VAN');
insert into m_product_unused(code,type)values(	'837091'	,'VAN');
insert into m_product_unused(code,type)values(	'837092'	,'VAN');
insert into m_product_unused(code,type)values(	'837093'	,'VAN');
insert into m_product_unused(code,type)values(	'837094'	,'VAN');
insert into m_product_unused(code,type)values(	'837095'	,'VAN');
insert into m_product_unused(code,type)values(	'837096'	,'VAN');
insert into m_product_unused(code,type)values(	'837097'	,'VAN');
insert into m_product_unused(code,type)values(	'837098'	,'VAN');
insert into m_product_unused(code,type)values(	'837099'	,'VAN');
insert into m_product_unused(code,type)values(	'837100'	,'VAN');
insert into m_product_unused(code,type)values(	'837101'	,'VAN');
insert into m_product_unused(code,type)values(	'833092'	,'VAN');
insert into m_product_unused(code,type)values(	'833093'	,'VAN');
insert into m_product_unused(code,type)values(	'833094'	,'VAN');
insert into m_product_unused(code,type)values(	'833095'	,'VAN');
insert into m_product_unused(code,type)values(	'833096'	,'VAN');
insert into m_product_unused(code,type)values(	'833097'	,'VAN');
insert into m_product_unused(code,type)values(	'833098'	,'VAN');
insert into m_product_unused(code,type)values(	'833099'	,'VAN');
insert into m_product_unused(code,type)values(	'833100'	,'VAN');
insert into m_product_unused(code,type)values(	'833101'	,'VAN');
insert into m_product_unused(code,type)values(	'833102'	,'VAN');
insert into m_product_unused(code,type)values(	'833103'	,'VAN');
insert into m_product_unused(code,type)values(	'833104'	,'VAN');
insert into m_product_unused(code,type)values(	'833105'	,'VAN');
insert into m_product_unused(code,type)values(	'833106'	,'VAN');
insert into m_product_unused(code,type)values(	'833107'	,'VAN');
insert into m_product_unused(code,type)values(	'833108'	,'VAN');
insert into m_product_unused(code,type)values(	'833109'	,'VAN');
insert into m_product_unused(code,type)values(	'833110'	,'VAN');
insert into m_product_unused(code,type)values(	'833111'	,'VAN');
insert into m_product_unused(code,type)values(	'833112'	,'VAN');
insert into m_product_unused(code,type)values(	'833113'	,'VAN');
insert into m_product_unused(code,type)values(	'833114'	,'VAN');
insert into m_product_unused(code,type)values(	'833115'	,'VAN');
insert into m_product_unused(code,type)values(	'833116'	,'VAN');
insert into m_product_unused(code,type)values(	'833117'	,'VAN');
insert into m_product_unused(code,type)values(	'833118'	,'VAN');
insert into m_product_unused(code,type)values(	'833119'	,'VAN');
insert into m_product_unused(code,type)values(	'833120'	,'VAN');
insert into m_product_unused(code,type)values(	'833121'	,'VAN');
insert into m_product_unused(code,type)values(	'833122'	,'VAN');
insert into m_product_unused(code,type)values(	'833123'	,'VAN');
insert into m_product_unused(code,type)values(	'833124'	,'VAN');
insert into m_product_unused(code,type)values(	'833125'	,'VAN');
insert into m_product_unused(code,type)values(	'833126'	,'VAN');
insert into m_product_unused(code,type)values(	'833127'	,'VAN');
insert into m_product_unused(code,type)values(	'833128'	,'VAN');
insert into m_product_unused(code,type)values(	'833129'	,'VAN');
insert into m_product_unused(code,type)values(	'833130'	,'VAN');
insert into m_product_unused(code,type)values(	'833131'	,'VAN');
insert into m_product_unused(code,type)values(	'833132'	,'VAN');
insert into m_product_unused(code,type)values(	'833133'	,'VAN');
insert into m_product_unused(code,type)values(	'833134'	,'VAN');
insert into m_product_unused(code,type)values(	'833135'	,'VAN');
insert into m_product_unused(code,type)values(	'833136'	,'VAN');
insert into m_product_unused(code,type)values(	'833137'	,'VAN');
insert into m_product_unused(code,type)values(	'833138'	,'VAN');
insert into m_product_unused(code,type)values(	'833139'	,'VAN');
insert into m_product_unused(code,type)values(	'833140'	,'VAN');
insert into m_product_unused(code,type)values(	'833141'	,'VAN');
insert into m_product_unused(code,type)values(	'833142'	,'VAN');
insert into m_product_unused(code,type)values(	'833143'	,'VAN');
insert into m_product_unused(code,type)values(	'833144'	,'VAN');
insert into m_product_unused(code,type)values(	'833145'	,'VAN');
insert into m_product_unused(code,type)values(	'833146'	,'VAN');
insert into m_product_unused(code,type)values(	'833147'	,'VAN');
insert into m_product_unused(code,type)values(	'833148'	,'VAN');
insert into m_product_unused(code,type)values(	'833149'	,'VAN');
insert into m_product_unused(code,type)values(	'833150'	,'VAN');
insert into m_product_unused(code,type)values(	'833151'	,'VAN');
insert into m_product_unused(code,type)values(	'833152'	,'VAN');
insert into m_product_unused(code,type)values(	'833153'	,'VAN');
insert into m_product_unused(code,type)values(	'834046'	,'VAN');
insert into m_product_unused(code,type)values(	'834047'	,'VAN');
insert into m_product_unused(code,type)values(	'834048'	,'VAN');
insert into m_product_unused(code,type)values(	'834049'	,'VAN');
insert into m_product_unused(code,type)values(	'834050'	,'VAN');
insert into m_product_unused(code,type)values(	'834051'	,'VAN');
insert into m_product_unused(code,type)values(	'834052'	,'VAN');
insert into m_product_unused(code,type)values(	'834053'	,'VAN');
insert into m_product_unused(code,type)values(	'834054'	,'VAN');
insert into m_product_unused(code,type)values(	'834055'	,'VAN');
insert into m_product_unused(code,type)values(	'834056'	,'VAN');
insert into m_product_unused(code,type)values(	'834057'	,'VAN');
insert into m_product_unused(code,type)values(	'834058'	,'VAN');
insert into m_product_unused(code,type)values(	'834059'	,'VAN');
insert into m_product_unused(code,type)values(	'834060'	,'VAN');
insert into m_product_unused(code,type)values(	'834061'	,'VAN');
insert into m_product_unused(code,type)values(	'834062'	,'VAN');
insert into m_product_unused(code,type)values(	'834063'	,'VAN');
insert into m_product_unused(code,type)values(	'834064'	,'VAN');
insert into m_product_unused(code,type)values(	'834065'	,'VAN');
insert into m_product_unused(code,type)values(	'834066'	,'VAN');
insert into m_product_unused(code,type)values(	'834067'	,'VAN');
insert into m_product_unused(code,type)values(	'834068'	,'VAN');
insert into m_product_unused(code,type)values(	'834069'	,'VAN');
insert into m_product_unused(code,type)values(	'834070'	,'VAN');
insert into m_product_unused(code,type)values(	'834071'	,'VAN');
insert into m_product_unused(code,type)values(	'834072'	,'VAN');
insert into m_product_unused(code,type)values(	'834073'	,'VAN');
insert into m_product_unused(code,type)values(	'834074'	,'VAN');
insert into m_product_unused(code,type)values(	'834075'	,'VAN');
insert into m_product_unused(code,type)values(	'834076'	,'VAN');
insert into m_product_unused(code,type)values(	'834077'	,'VAN');
insert into m_product_unused(code,type)values(	'834078'	,'VAN');
insert into m_product_unused(code,type)values(	'834079'	,'VAN');
insert into m_product_unused(code,type)values(	'834080'	,'VAN');
insert into m_product_unused(code,type)values(	'834081'	,'VAN');
insert into m_product_unused(code,type)values(	'834082'	,'VAN');
insert into m_product_unused(code,type)values(	'834083'	,'VAN');
insert into m_product_unused(code,type)values(	'834084'	,'VAN');
insert into m_product_unused(code,type)values(	'834085'	,'VAN');
insert into m_product_unused(code,type)values(	'834086'	,'VAN');
insert into m_product_unused(code,type)values(	'834087'	,'VAN');
insert into m_product_unused(code,type)values(	'834088'	,'VAN');
insert into m_product_unused(code,type)values(	'834089'	,'VAN');
insert into m_product_unused(code,type)values(	'834090'	,'VAN');
insert into m_product_unused(code,type)values(	'834091'	,'VAN');
insert into m_product_unused(code,type)values(	'834092'	,'VAN');
insert into m_product_unused(code,type)values(	'834093'	,'VAN');
insert into m_product_unused(code,type)values(	'834094'	,'VAN');
insert into m_product_unused(code,type)values(	'834095'	,'VAN');
insert into m_product_unused(code,type)values(	'834096'	,'VAN');
insert into m_product_unused(code,type)values(	'834097'	,'VAN');
insert into m_product_unused(code,type)values(	'834098'	,'VAN');
insert into m_product_unused(code,type)values(	'834099'	,'VAN');
insert into m_product_unused(code,type)values(	'834100'	,'VAN');
insert into m_product_unused(code,type)values(	'834101'	,'VAN');
insert into m_product_unused(code,type)values(	'834102'	,'VAN');
insert into m_product_unused(code,type)values(	'834103'	,'VAN');
insert into m_product_unused(code,type)values(	'834104'	,'VAN');
insert into m_product_unused(code,type)values(	'834105'	,'VAN');
insert into m_product_unused(code,type)values(	'834106'	,'VAN');
insert into m_product_unused(code,type)values(	'834107'	,'VAN');
insert into m_product_unused(code,type)values(	'834108'	,'VAN');
insert into m_product_unused(code,type)values(	'836023'	,'VAN');
insert into m_product_unused(code,type)values(	'836024'	,'VAN');
insert into m_product_unused(code,type)values(	'836025'	,'VAN');
insert into m_product_unused(code,type)values(	'836026'	,'VAN');
insert into m_product_unused(code,type)values(	'836027'	,'VAN');
insert into m_product_unused(code,type)values(	'836028'	,'VAN');
insert into m_product_unused(code,type)values(	'836029'	,'VAN');
insert into m_product_unused(code,type)values(	'837102'	,'VAN');
insert into m_product_unused(code,type)values(	'837103'	,'VAN');
insert into m_product_unused(code,type)values(	'837104'	,'VAN');
insert into m_product_unused(code,type)values(	'837105'	,'VAN');
insert into m_product_unused(code,type)values(	'837106'	,'VAN');
insert into m_product_unused(code,type)values(	'837107'	,'VAN');
insert into m_product_unused(code,type)values(	'837108'	,'VAN');
insert into m_product_unused(code,type)values(	'837109'	,'VAN');
insert into m_product_unused(code,type)values(	'837110'	,'VAN');
insert into m_product_unused(code,type)values(	'837111'	,'VAN');
insert into m_product_unused(code,type)values(	'837112'	,'VAN');
insert into m_product_unused(code,type)values(	'837113'	,'VAN');
insert into m_product_unused(code,type)values(	'837114'	,'VAN');
insert into m_product_unused(code,type)values(	'837115'	,'VAN');
insert into m_product_unused(code,type)values(	'837116'	,'VAN');
insert into m_product_unused(code,type)values(	'837117'	,'VAN');
insert into m_product_unused(code,type)values(	'837118'	,'VAN');
insert into m_product_unused(code,type)values(	'837119'	,'VAN');
insert into m_product_unused(code,type)values(	'837120'	,'VAN');
insert into m_product_unused(code,type)values(	'837121'	,'VAN');
insert into m_product_unused(code,type)values(	'837122'	,'VAN');
insert into m_product_unused(code,type)values(	'837123'	,'VAN');
insert into m_product_unused(code,type)values(	'837124'	,'VAN');
insert into m_product_unused(code,type)values(	'837125'	,'VAN');
insert into m_product_unused(code,type)values(	'837126'	,'VAN');
insert into m_product_unused(code,type)values(	'837127'	,'VAN');
insert into m_product_unused(code,type)values(	'837128'	,'VAN');
insert into m_product_unused(code,type)values(	'837129'	,'VAN');
insert into m_product_unused(code,type)values(	'837130'	,'VAN');
insert into m_product_unused(code,type)values(	'837131'	,'VAN');
insert into m_product_unused(code,type)values(	'837132'	,'VAN');
insert into m_product_unused(code,type)values(	'823049'	,'VAN');
insert into m_product_unused(code,type)values(	'823050'	,'VAN');
insert into m_product_unused(code,type)values(	'823051'	,'VAN');
insert into m_product_unused(code,type)values(	'823052'	,'VAN');
insert into m_product_unused(code,type)values(	'823053'	,'VAN');
insert into m_product_unused(code,type)values(	'823054'	,'VAN');
insert into m_product_unused(code,type)values(	'824034'	,'VAN');
insert into m_product_unused(code,type)values(	'824035'	,'VAN');
insert into m_product_unused(code,type)values(	'824036'	,'VAN');
insert into m_product_unused(code,type)values(	'824037'	,'VAN');
insert into m_product_unused(code,type)values(	'824038'	,'VAN');
insert into m_product_unused(code,type)values(	'824039'	,'VAN');
insert into m_product_unused(code,type)values(	'824040'	,'VAN');
insert into m_product_unused(code,type)values(	'824041'	,'VAN');
insert into m_product_unused(code,type)values(	'824042'	,'VAN');
insert into m_product_unused(code,type)values(	'824043'	,'VAN');
insert into m_product_unused(code,type)values(	'824044'	,'VAN');
insert into m_product_unused(code,type)values(	'824045'	,'VAN');
insert into m_product_unused(code,type)values(	'824046'	,'VAN');
insert into m_product_unused(code,type)values(	'824047'	,'VAN');
insert into m_product_unused(code,type)values(	'824048'	,'VAN');
insert into m_product_unused(code,type)values(	'824049'	,'VAN');
insert into m_product_unused(code,type)values(	'824050'	,'VAN');
insert into m_product_unused(code,type)values(	'824051'	,'VAN');
insert into m_product_unused(code,type)values(	'833154'	,'VAN');
insert into m_product_unused(code,type)values(	'833155'	,'VAN');
insert into m_product_unused(code,type)values(	'833156'	,'VAN');
insert into m_product_unused(code,type)values(	'833157'	,'VAN');
insert into m_product_unused(code,type)values(	'833158'	,'VAN');
insert into m_product_unused(code,type)values(	'833159'	,'VAN');
insert into m_product_unused(code,type)values(	'833160'	,'VAN');
insert into m_product_unused(code,type)values(	'833161'	,'VAN');
insert into m_product_unused(code,type)values(	'833162'	,'VAN');
insert into m_product_unused(code,type)values(	'833163'	,'VAN');
insert into m_product_unused(code,type)values(	'833164'	,'VAN');
insert into m_product_unused(code,type)values(	'833165'	,'VAN');
insert into m_product_unused(code,type)values(	'833166'	,'VAN');
insert into m_product_unused(code,type)values(	'833167'	,'VAN');
insert into m_product_unused(code,type)values(	'833168'	,'VAN');
insert into m_product_unused(code,type)values(	'833169'	,'VAN');
insert into m_product_unused(code,type)values(	'833170'	,'VAN');
insert into m_product_unused(code,type)values(	'833171'	,'VAN');
insert into m_product_unused(code,type)values(	'834109'	,'VAN');
insert into m_product_unused(code,type)values(	'834110'	,'VAN');
insert into m_product_unused(code,type)values(	'834111'	,'VAN');
insert into m_product_unused(code,type)values(	'834112'	,'VAN');
insert into m_product_unused(code,type)values(	'834113'	,'VAN');
insert into m_product_unused(code,type)values(	'834114'	,'VAN');
insert into m_product_unused(code,type)values(	'834115'	,'VAN');
insert into m_product_unused(code,type)values(	'834116'	,'VAN');
insert into m_product_unused(code,type)values(	'834117'	,'VAN');
insert into m_product_unused(code,type)values(	'834118'	,'VAN');
insert into m_product_unused(code,type)values(	'834119'	,'VAN');
insert into m_product_unused(code,type)values(	'834120'	,'VAN');
insert into m_product_unused(code,type)values(	'834121'	,'VAN');
insert into m_product_unused(code,type)values(	'834122'	,'VAN');
insert into m_product_unused(code,type)values(	'834123'	,'VAN');
insert into m_product_unused(code,type)values(	'834124'	,'VAN');
insert into m_product_unused(code,type)values(	'834125'	,'VAN');
insert into m_product_unused(code,type)values(	'834126'	,'VAN');
insert into m_product_unused(code,type)values(	'834127'	,'VAN');
insert into m_product_unused(code,type)values(	'834128'	,'VAN');
insert into m_product_unused(code,type)values(	'834129'	,'VAN');
insert into m_product_unused(code,type)values(	'834130'	,'VAN');
insert into m_product_unused(code,type)values(	'834131'	,'VAN');
insert into m_product_unused(code,type)values(	'834132'	,'VAN');
insert into m_product_unused(code,type)values(	'834133'	,'VAN');
insert into m_product_unused(code,type)values(	'834134'	,'VAN');
insert into m_product_unused(code,type)values(	'834135'	,'VAN');
insert into m_product_unused(code,type)values(	'834136'	,'VAN');
insert into m_product_unused(code,type)values(	'834137'	,'VAN');
insert into m_product_unused(code,type)values(	'834138'	,'VAN');
insert into m_product_unused(code,type)values(	'834139'	,'VAN');
insert into m_product_unused(code,type)values(	'834140'	,'VAN');
insert into m_product_unused(code,type)values(	'834141'	,'VAN');
insert into m_product_unused(code,type)values(	'834142'	,'VAN');
insert into m_product_unused(code,type)values(	'834143'	,'VAN');
insert into m_product_unused(code,type)values(	'834144'	,'VAN');
insert into m_product_unused(code,type)values(	'834145'	,'VAN');
insert into m_product_unused(code,type)values(	'834146'	,'VAN');
insert into m_product_unused(code,type)values(	'834147'	,'VAN');
insert into m_product_unused(code,type)values(	'834148'	,'VAN');
insert into m_product_unused(code,type)values(	'834149'	,'VAN');
insert into m_product_unused(code,type)values(	'834150'	,'VAN');
insert into m_product_unused(code,type)values(	'834151'	,'VAN');
insert into m_product_unused(code,type)values(	'834152'	,'VAN');
insert into m_product_unused(code,type)values(	'834153'	,'VAN');
insert into m_product_unused(code,type)values(	'834154'	,'VAN');
insert into m_product_unused(code,type)values(	'834155'	,'VAN');
insert into m_product_unused(code,type)values(	'834156'	,'VAN');
insert into m_product_unused(code,type)values(	'834157'	,'VAN');
insert into m_product_unused(code,type)values(	'834158'	,'VAN');
insert into m_product_unused(code,type)values(	'834159'	,'VAN');
insert into m_product_unused(code,type)values(	'834160'	,'VAN');
insert into m_product_unused(code,type)values(	'834161'	,'VAN');
insert into m_product_unused(code,type)values(	'834162'	,'VAN');
insert into m_product_unused(code,type)values(	'834163'	,'VAN');
insert into m_product_unused(code,type)values(	'834164'	,'VAN');
insert into m_product_unused(code,type)values(	'834165'	,'VAN');
insert into m_product_unused(code,type)values(	'834166'	,'VAN');
insert into m_product_unused(code,type)values(	'834167'	,'VAN');
insert into m_product_unused(code,type)values(	'834168'	,'VAN');
insert into m_product_unused(code,type)values(	'834169'	,'VAN');
insert into m_product_unused(code,type)values(	'834170'	,'VAN');
insert into m_product_unused(code,type)values(	'834171'	,'VAN');

