CREATE TABLE `m_uom_class` (
  `UOM_CLASS_ID` varchar(20) NOT NULL default '0',
  `NAME` varchar(50) NOT NULL,
  `DESCRIPTION` varchar(255) default NULL,
  `DISABLE_DATE` date default NULL,
  PRIMARY KEY  (`UOM_CLASS_ID`),
  UNIQUE KEY `XPKM_UOM_CLASS` (`UOM_CLASS_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;



ALTER TABLE `m_uom` ADD DISABLE_DATE DATE NOT NULL,
  ADD UOM_CLASS_ID varchar(50) NOT NULL;

  
  

DROP TABLE M_UOM_CONVERSION
;



CREATE TABLE M_UOM_CONVERSION
(
	PRODUCT_ID            INTEGER NULL,
	UOM_ID                VARCHAR(20) NULL,
	CONVERSION_RATE       DECIMAL(20,20) NULL,
	DISABLE_DATE          DATE NULL
)
;


CREATE INDEX XIF1M_UOM_CONVERSION ON M_UOM_CONVERSION
(
	PRODUCT_ID
)
;




DROP TABLE M_UOM_CLASS_CONVERSION
;



CREATE TABLE M_UOM_CLASS_CONVERSION
(
	PRODUCT_ID            INTEGER NULL,
	UOM_FROM_ID           VARCHAR(20) NULL,
	UOM_TO_ID             VARCHAR(20) NULL,
	CONVERSION_RATE       DECIMAL(20,20) NULL,
	DISABLE_DATE          DATE NULL
)
;


CREATE INDEX XIF1M_UOM_CLASS_CONVERSION ON M_UOM_CLASS_CONVERSION
(
	PRODUCT_ID
)
;



CREATE INDEX XIF2M_UOM_CLASS_CONVERSION ON M_UOM_CLASS_CONVERSION
(
	UOM_FROM_ID
)
;



CREATE INDEX XIF3M_UOM_CLASS_CONVERSION ON M_UOM_CLASS_CONVERSION
(
	UOM_TO_ID
)
;



ALTER TABLE M_UOM_CLASS_CONVERSION
	ADD FOREIGN KEY R_50 (PRODUCT_ID) REFERENCES M_PRODUCT(PRODUCT_ID)
;


ALTER TABLE M_UOM_CLASS_CONVERSION
	ADD FOREIGN KEY R_51 (UOM_FROM_ID) REFERENCES M_UOM(UOM_ID)
;


ALTER TABLE M_UOM_CLASS_CONVERSION
	ADD FOREIGN KEY R_52 (UOM_TO_ID) REFERENCES M_UOM(UOM_ID)
;

ALTER TABLE `M_UOM_CLASS_CONVERSION` RENAME `m_uom_class_conversion`;
ALTER TABLE `m_uom_class_conversion` ENGINE = InnoDB;
ALTER TABLE `M_UOM_CONVERSION` RENAME `m_uom_conversion`;
ALTER TABLE `m_uom_conversion` ENGINE = InnoDB;
ALTER TABLE `m_uom` CHANGE `DISABLE_DATE` DISABLE_DATE DATE,
  CHANGE `UOM_CLASS_ID` UOM_CLASS_ID varchar(50);

ALTER TABLE `m_uom_conversion` CHANGE `CONVERSION_RATE` CONVERSION_RATE VARCHAR(20);
ALTER TABLE `m_uom_class_conversion` CHANGE `CONVERSION_RATE` CONVERSION_RATE VARCHAR(20);
