
CREATE TABLE M_MEMBER_FOLLOW
(
	MEMBER_FOLLOW_ID      INTEGER NOT NULL,
	CUSTOMER_ID           INTEGER NOT NULL,
	USER_ID               INTEGER NOT NULL,
  	FOLLOW_DATE           DATE NULL,
	FOLLOW_TIME           VARCHAR(5) NULL,
	FOLLOW_BY             VARCHAR(5) NULL,
	FOLLOW_DETAIL         VARCHAR(1000) NULL,
	RENEWED               CHAR(1) NOT NULL DEFAULT 'N',
  	ISACTIVE              CHAR(1) NOT NULL DEFAULT 'Y',
	CREATED               TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CREATED_BY            INTEGER NOT NULL,
	UPDATED               TIMESTAMP NULL DEFAULT NULL,
	UPDATED_BY            INTEGER NULL
)engine=innodb default charset=tis620
;



CREATE UNIQUE INDEX XPKM_MEMBER_FOLLOW ON M_MEMBER_FOLLOW
(
	MEMBER_FOLLOW_ID
)
;



ALTER TABLE M_MEMBER_FOLLOW
	ADD  PRIMARY KEY (MEMBER_FOLLOW_ID)
;



CREATE INDEX XIF1M_MEMBER_FOLLOW ON M_MEMBER_FOLLOW
(
	CUSTOMER_ID
)
;



CREATE INDEX XIF2M_MEMBER_FOLLOW ON M_MEMBER_FOLLOW
(
	USER_ID
)
;



ALTER TABLE M_MEMBER_FOLLOW
	ADD FOREIGN KEY R_99 (CUSTOMER_ID) REFERENCES M_CUSTOMER(CUSTOMER_ID)
;


ALTER TABLE M_MEMBER_FOLLOW
	ADD FOREIGN KEY R_100 (USER_ID) REFERENCES AD_USER(USER_ID)
;


