
CREATE TABLE M_MEMBER_RENEW
(
	RENEW_ID              INTEGER NOT NULL,
	CUSTOMER_ID           INTEGER NULL,
	EXPIRED_DATE          DATE NULL,
	RENEWED_DATE          DATE NULL,
	MEMBER_TYPE           VARCHAR(5) NULL,
	APPLIED_DATE          DATE NULL,
	CREATED_BY            INTEGER NULL,
	CREATED               TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	UPDATED_BY            INTEGER NULL,
	UPDATED               TIMESTAMP NULL
)
;



CREATE UNIQUE INDEX XPKM_MEMEBER_RENEW ON M_MEMBER_RENEW
(
	RENEW_ID
)
;



ALTER TABLE M_MEMBER_RENEW
	ADD  PRIMARY KEY (RENEW_ID)
;



CREATE INDEX XIF1M_MEMEBER_RENEW ON M_MEMBER_RENEW
(
	CUSTOMER_ID
)
;



ALTER TABLE M_MEMBER_RENEW
	ADD FOREIGN KEY R_82 (CUSTOMER_ID) REFERENCES M_CUSTOMER(CUSTOMER_ID)
;


ALTER TABLE `m_member_renew` CHARACTER SET tis620 COLLATE tis620_thai_ci,
  CHANGE `MEMBER_TYPE` MEMBER_TYPE VARCHAR(5) CHARACTER SET tis620 COLLATE tis620_thai_ci;
ALTER TABLE `m_member_renew` DROP FOREIGN KEY m_member_renew_ibfk_1;
ALTER TABLE `m_member_renew` ADD CONSTRAINT m_member_renew_ibfk_1 FOREIGN KEY (CUSTOMER_ID) REFERENCES m_customer (CUSTOMER_ID) ON UPDATE RESTRICT ON DELETE RESTRICT;
