

DROP TABLE M_ADDRESS
;




DROP TABLE M_CONTACT
;




DROP TABLE M_MEMBER_PRODUCT
;




DROP TABLE T_VISIT_LINE
;




DROP TABLE T_VISIT
;




DROP TABLE M_CUSTOMER
;



CREATE TABLE M_ADDRESS
(
	ADDRESS_ID            INTEGER NOT NULL,
	ISACTIVE              CHAR(1) NOT NULL DEFAULT 'Y',
	LINE1                 VARCHAR(100) NOT NULL,
	LINE2                 VARCHAR(100) NOT NULL,
	LINE3                 VARCHAR(100) NOT NULL,
	LINE4                 VARCHAR(100) NOT NULL,
	POSTAL_CODE           VARCHAR(5) NOT NULL,
	COUNTRY               VARCHAR(20) NULL,
	PROVINCE_ID           INTEGER NULL,
	PURPOSE               CHAR(2) NULL,
	DISTRICT_ID           INTEGER NULL,
	CUSTOMER_ID           INTEGER NULL
)
;



CREATE UNIQUE INDEX XPKM_ADDRESS ON M_ADDRESS
(
	ADDRESS_ID
)
;



ALTER TABLE M_ADDRESS
	ADD  PRIMARY KEY (ADDRESS_ID)
;



CREATE INDEX XIF1M_ADDRESS ON M_ADDRESS
(
	CUSTOMER_ID
)
;



CREATE INDEX XIF2M_ADDRESS ON M_ADDRESS
(
	PROVINCE_ID
)
;



CREATE INDEX XIF3M_ADDRESS ON M_ADDRESS
(
	DISTRICT_ID
)
;



CREATE TABLE M_CONTACT
(
	CONTACT_ID            INTEGER NOT NULL,
	CUSTOMER_ID           INTEGER NULL,
	CONTACT_TO            VARCHAR(100) NULL,
	PHONE                 VARCHAR(100) NULL,
	FAX                   VARCHAR(100) NULL,
	ISACTIVE              CHAR(1) NOT NULL DEFAULT 'Y',
	RELATION              VARCHAR(100) NULL
)
;



CREATE UNIQUE INDEX XPKM_CONTACT ON M_CONTACT
(
	CONTACT_ID
)
;



ALTER TABLE M_CONTACT
	ADD  PRIMARY KEY (CONTACT_ID)
;



CREATE INDEX XIF1M_CONTACT ON M_CONTACT
(
	CUSTOMER_ID
)
;



CREATE TABLE M_CUSTOMER
(
	CUSTOMER_ID           INTEGER NOT NULL,
	REFERENCE_ID          INTEGER NULL,
	CODE                  VARCHAR(20) NULL,
	NAME                  VARCHAR(100) NULL,
	NAME2                 VARCHAR(100) NULL,
	CUSTOMER_TYPE         VARCHAR(5) NULL,
	TAX_NO                VARCHAR(20) NULL,
	TERRITORY             VARCHAR(5) NULL,
	WEBSITE               VARCHAR(100) NULL,
	BUSINESS_TYPE         VARCHAR(100) NULL,
	ISACTIVE              CHAR(1) NOT NULL DEFAULT 'Y',
	USER_ID               INTEGER NULL,
	PERSON_ID_NO          VARCHAR(20) NULL,
	EMAIL                 VARCHAR(100) NULL,
	CREDIT_CHECK          CHAR(1) NULL DEFAULT 'N',
	REGISTER_DATE         DATE NULL,
	PAYMENT_TERM          CHAR(5) NULL,
	VAT_CODE              CHAR(5) NULL,
	CREDIT_LIMIT          DECIMAL(10,2) NULL,
	BIRTHDAY              DATE NULL,
	OCCUPATION            VARCHAR(100) NULL,
	SHIPPING_METHOD       VARCHAR(5) NULL,
	ORDER_DATE            VARCHAR(5) NULL,
	SHIPPING_DATE         VARCHAR(5) NULL,
	SHIPPING_ROUTE        VARCHAR(5) NULL,
	MONHTLY_INCOME        DECIMAL(10,2) NULL,
	CHROLESTEROL          DECIMAL NULL,
	MEMBER_LEVEL          VARCHAR(5) NULL,
	RECOMMENDED_BY        VARCHAR(100) NULL,
	CANCEL_REASON         VARCHAR(255) NULL,
	MEMBER_TYPE           VARCHAR(5) NULL,
	PRODUCT_CATEGORY_ID   INTEGER NULL,
	CREATED               TIMESTAMP NULL,
	CREATED_BY            INTEGER NULL,
	UPDATED               TIMESTAMP NULL,
	UPDATED_BY            INTEGER NULL,
	ORDER_AMOUNT_PERIOD   INTEGER NULL,
	PAYMENT_METHOD        VARCHAR(5) NULL,
	PARENT_CUSTOMER_ID    INTEGER NULL,
	TRANSIT_NAME          VARCHAR(100) NULL
)
;



CREATE UNIQUE INDEX XPKM_CUSTOMER ON M_CUSTOMER
(
	CUSTOMER_ID
)
;



ALTER TABLE M_CUSTOMER
	ADD  PRIMARY KEY (CUSTOMER_ID)
;



CREATE INDEX XIF1M_CUSTOMER ON M_CUSTOMER
(
	PRODUCT_CATEGORY_ID
)
;



CREATE INDEX XIF2M_CUSTOMER ON M_CUSTOMER
(
	USER_ID
)
;



CREATE TABLE M_MEMBER_PRODUCT
(
	PRODUCT_ID            INTEGER NULL,
	CUSTOMER_ID           INTEGER NULL,
	MEMBER_PRODUCT_ID     INTEGER NULL,
	ORDER_QTY             INTEGER NULL,
	UOM_ID                VARCHAR(20) NULL
)
;



CREATE UNIQUE INDEX XPKM_MEMBER_PRODUCT ON M_MEMBER_PRODUCT
(
	MEMBER_PRODUCT_ID
)
;



ALTER TABLE M_MEMBER_PRODUCT
	ADD  PRIMARY KEY (MEMBER_PRODUCT_ID)
;



CREATE INDEX XIF1M_MEMBER_PRODUCT ON M_MEMBER_PRODUCT
(
	PRODUCT_ID
)
;



CREATE INDEX XIF2M_MEMBER_PRODUCT ON M_MEMBER_PRODUCT
(
	UOM_ID
)
;



CREATE INDEX XIF3M_MEMBER_PRODUCT ON M_MEMBER_PRODUCT
(
	CUSTOMER_ID
)
;



CREATE TABLE T_VISIT
(
	VISIT_ID              INTEGER NOT NULL,
	CODE                  VARCHAR(20) NOT NULL,
	VISIT_DATE            DATE NOT NULL,
	VISIT_TIME            VARCHAR(5) NOT NULL,
	CUSTOMER_ID           INTEGER NOT NULL,
	SALES_CLOSED          CHAR(1) NOT NULL DEFAULT 'N',
	UNCLOSED_REASON       VARCHAR(5) NULL,
	ISACTIVE              CHAR(1) NOT NULL DEFAULT 'Y',
	CREATED               TIMESTAMP NULL,
	CREATED_BY            INTEGER NULL,
	UPDATED               TIMESTAMP NULL,
	UPDATED_BY            INTEGER NULL,
	USER_ID               INTEGER NULL
)
;



CREATE UNIQUE INDEX XPKT_CUSTOMER_VISIT ON T_VISIT
(
	VISIT_ID
)
;



ALTER TABLE T_VISIT
	ADD  PRIMARY KEY (VISIT_ID)
;



CREATE INDEX XIF1T_CUSTOMER_VISIT ON T_VISIT
(
	CUSTOMER_ID
)
;



CREATE INDEX XIF2T_CUSTOMER_VISIT ON T_VISIT
(
	USER_ID
)
;



CREATE TABLE T_VISIT_LINE
(
	VISIT_LINE_ID         INTEGER NOT NULL,
	LINE_NO               CHAR(18) NULL,
	PRODUCT_ID            INTEGER NULL,
	ISACTIVE              CHAR(1) NOT NULL DEFAULT 'Y',
	CREATED               TIMESTAMP NULL,
	CREATED_BY            INTEGER NULL,
	UPDATED               TIMESTAMP NULL,
	UPDATED_BY            INTEGER NULL,
	AMOUNT                DECIMAL NULL,
	VISIT_ID              INTEGER NULL,
	UOM_ID                VARCHAR(20) NULL
)
;



CREATE UNIQUE INDEX XPKT_VISIT_LINE ON T_VISIT_LINE
(
	VISIT_LINE_ID
)
;



ALTER TABLE T_VISIT_LINE
	ADD  PRIMARY KEY (VISIT_LINE_ID)
;



CREATE INDEX XIF1T_VISIT_LINE ON T_VISIT_LINE
(
	VISIT_ID
)
;



CREATE INDEX XIF2T_VISIT_LINE ON T_VISIT_LINE
(
	PRODUCT_ID
)
;



CREATE INDEX XIF3T_VISIT_LINE ON T_VISIT_LINE
(
	UOM_ID
)
;



ALTER TABLE M_ADDRESS
	ADD FOREIGN KEY R_5 (CUSTOMER_ID) REFERENCES M_CUSTOMER(CUSTOMER_ID)
;


ALTER TABLE M_ADDRESS
	ADD FOREIGN KEY R_6 (PROVINCE_ID) REFERENCES M_PROVINCE(PROVINCE_ID)
;


ALTER TABLE M_ADDRESS
	ADD FOREIGN KEY R_7 (DISTRICT_ID) REFERENCES M_DISTRICT(DISTRICT_ID)
;



ALTER TABLE M_CONTACT
	ADD FOREIGN KEY R_9 (CUSTOMER_ID) REFERENCES M_CUSTOMER(CUSTOMER_ID)
;



ALTER TABLE M_CUSTOMER
	ADD FOREIGN KEY R_12 (PRODUCT_CATEGORY_ID) REFERENCES M_PRODUCT_CATEGORY(PRODUCT_CATEGORY_ID)
;


ALTER TABLE M_CUSTOMER
	ADD FOREIGN KEY R_14 (USER_ID) REFERENCES AD_USER(USER_ID)
;



ALTER TABLE M_MEMBER_PRODUCT
	ADD FOREIGN KEY R_10 (PRODUCT_ID) REFERENCES M_PRODUCT(PRODUCT_ID)
;


ALTER TABLE M_MEMBER_PRODUCT
	ADD FOREIGN KEY R_11 (UOM_ID) REFERENCES M_UOM(UOM_ID)
;


ALTER TABLE M_MEMBER_PRODUCT
	ADD FOREIGN KEY R_13 (CUSTOMER_ID) REFERENCES M_CUSTOMER(CUSTOMER_ID)
;



ALTER TABLE T_VISIT
	ADD FOREIGN KEY R_15 (CUSTOMER_ID) REFERENCES M_CUSTOMER(CUSTOMER_ID)
;


ALTER TABLE T_VISIT
	ADD FOREIGN KEY R_29 (USER_ID) REFERENCES AD_USER(USER_ID)
;



ALTER TABLE T_VISIT_LINE
	ADD FOREIGN KEY R_16 (VISIT_ID) REFERENCES T_VISIT(VISIT_ID)
;


ALTER TABLE T_VISIT_LINE
	ADD FOREIGN KEY R_17 (PRODUCT_ID) REFERENCES M_PRODUCT(PRODUCT_ID)
;


ALTER TABLE T_VISIT_LINE
	ADD FOREIGN KEY R_18 (UOM_ID) REFERENCES M_UOM(UOM_ID)
;

ALTER TABLE `m_customer` CHARACTER SET tis620 COLLATE tis620_thai_ci,
  CHANGE `CODE` CODE VARCHAR(20) CHARACTER SET tis620 COLLATE tis620_thai_ci,
  CHANGE `NAME` NAME VARCHAR(100) CHARACTER SET tis620 COLLATE tis620_thai_ci,
  CHANGE `NAME2` NAME2 VARCHAR(100) CHARACTER SET tis620 COLLATE tis620_thai_ci,
  CHANGE `CUSTOMER_TYPE` CUSTOMER_TYPE VARCHAR(5) CHARACTER SET tis620 COLLATE tis620_thai_ci,
  CHANGE `TAX_NO` TAX_NO VARCHAR(20) CHARACTER SET tis620 COLLATE tis620_thai_ci,
  CHANGE `TERRITORY` TERRITORY VARCHAR(5) CHARACTER SET tis620 COLLATE tis620_thai_ci,
  CHANGE `WEBSITE` WEBSITE VARCHAR(100) CHARACTER SET tis620 COLLATE tis620_thai_ci,
  CHANGE `BUSINESS_TYPE` BUSINESS_TYPE VARCHAR(100) CHARACTER SET tis620 COLLATE tis620_thai_ci,
  CHANGE `PERSON_ID_NO` PERSON_ID_NO VARCHAR(20) CHARACTER SET tis620 COLLATE tis620_thai_ci,
  CHANGE `EMAIL` EMAIL VARCHAR(100) CHARACTER SET tis620 COLLATE tis620_thai_ci,
  CHANGE `OCCUPATION` OCCUPATION VARCHAR(100) CHARACTER SET tis620 COLLATE tis620_thai_ci,
  CHANGE `SHIPPING_METHOD` SHIPPING_METHOD VARCHAR(5) CHARACTER SET tis620 COLLATE tis620_thai_ci,
  CHANGE `ORDER_DATE` ORDER_DATE VARCHAR(5) CHARACTER SET tis620 COLLATE tis620_thai_ci,
  CHANGE `SHIPPING_DATE` SHIPPING_DATE VARCHAR(5) CHARACTER SET tis620 COLLATE tis620_thai_ci,
  CHANGE `SHIPPING_ROUTE` SHIPPING_ROUTE VARCHAR(5) CHARACTER SET tis620 COLLATE tis620_thai_ci,
  CHANGE `MEMBER_LEVEL` MEMBER_LEVEL VARCHAR(5) CHARACTER SET tis620 COLLATE tis620_thai_ci,
  CHANGE `RECOMMENDED_BY` RECOMMENDED_BY VARCHAR(100) CHARACTER SET tis620 COLLATE tis620_thai_ci,
  CHANGE `CANCEL_REASON` CANCEL_REASON VARCHAR(255) CHARACTER SET tis620 COLLATE tis620_thai_ci,
  CHANGE `MEMBER_TYPE` MEMBER_TYPE VARCHAR(5) CHARACTER SET tis620 COLLATE tis620_thai_ci,
  CHANGE `PAYMENT_METHOD` PAYMENT_METHOD VARCHAR(5) CHARACTER SET tis620 COLLATE tis620_thai_ci,
  CHANGE `TRANSIT_NAME` TRANSIT_NAME VARCHAR(100) CHARACTER SET tis620 COLLATE tis620_thai_ci;
ALTER TABLE `m_customer` DROP FOREIGN KEY m_customer_ibfk_2,
  DROP FOREIGN KEY m_customer_ibfk_1;
ALTER TABLE `m_customer` ADD CONSTRAINT m_customer_ibfk_2 FOREIGN KEY (USER_ID) REFERENCES ad_user (USER_ID) ON UPDATE RESTRICT ON DELETE RESTRICT,
  ADD CONSTRAINT m_customer_ibfk_1 FOREIGN KEY (PRODUCT_CATEGORY_ID) REFERENCES m_product_category (PRODUCT_CATEGORY_ID) ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE `m_address` CHARACTER SET tis620 COLLATE tis620_thai_ci,
  CHANGE `LINE1` LINE1 VARCHAR(100) CHARACTER SET tis620 COLLATE tis620_thai_ci NOT NULL,
  CHANGE `LINE2` LINE2 VARCHAR(100) CHARACTER SET tis620 COLLATE tis620_thai_ci NOT NULL,
  CHANGE `LINE3` LINE3 VARCHAR(100) CHARACTER SET tis620 COLLATE tis620_thai_ci NOT NULL,
  CHANGE `LINE4` LINE4 VARCHAR(100) CHARACTER SET tis620 COLLATE tis620_thai_ci NOT NULL,
  CHANGE `POSTAL_CODE` POSTAL_CODE VARCHAR(5) CHARACTER SET tis620 COLLATE tis620_thai_ci NOT NULL,
  CHANGE `COUNTRY` COUNTRY VARCHAR(20) CHARACTER SET tis620 COLLATE tis620_thai_ci;
ALTER TABLE `m_address` DROP FOREIGN KEY m_address_ibfk_3,
  DROP FOREIGN KEY m_address_ibfk_1,
  DROP FOREIGN KEY m_address_ibfk_2;
ALTER TABLE `m_address` ADD CONSTRAINT m_address_ibfk_3 FOREIGN KEY (DISTRICT_ID) REFERENCES m_district (DISTRICT_ID) ON UPDATE RESTRICT ON DELETE RESTRICT,
  ADD CONSTRAINT m_address_ibfk_1 FOREIGN KEY (CUSTOMER_ID) REFERENCES m_customer (CUSTOMER_ID) ON UPDATE RESTRICT ON DELETE RESTRICT,
  ADD CONSTRAINT m_address_ibfk_2 FOREIGN KEY (PROVINCE_ID) REFERENCES m_province (PROVINCE_ID) ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE `m_contact` CHARACTER SET tis620 COLLATE tis620_thai_ci,
  CHANGE `CONTACT_TO` CONTACT_TO VARCHAR(100) CHARACTER SET tis620 COLLATE tis620_thai_ci,
  CHANGE `PHONE` PHONE VARCHAR(100) CHARACTER SET tis620 COLLATE tis620_thai_ci,
  CHANGE `FAX` FAX VARCHAR(100) CHARACTER SET tis620 COLLATE tis620_thai_ci,
  CHANGE `RELATION` RELATION VARCHAR(100) CHARACTER SET tis620 COLLATE tis620_thai_ci;
ALTER TABLE `m_contact` DROP FOREIGN KEY m_contact_ibfk_1;
ALTER TABLE `m_contact` ADD CONSTRAINT m_contact_ibfk_1 FOREIGN KEY (CUSTOMER_ID) REFERENCES m_customer (CUSTOMER_ID) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE `t_visit` CHARACTER SET tis620 COLLATE tis620_thai_ci,
  CHANGE `CODE` CODE VARCHAR(20) CHARACTER SET tis620 COLLATE tis620_thai_ci NOT NULL,
  CHANGE `VISIT_TIME` VISIT_TIME VARCHAR(5) CHARACTER SET tis620 COLLATE tis620_thai_ci NOT NULL,
  CHANGE `UNCLOSED_REASON` UNCLOSED_REASON VARCHAR(5) CHARACTER SET tis620 COLLATE tis620_thai_ci;
ALTER TABLE `t_visit` DROP FOREIGN KEY t_visit_ibfk_2,
  DROP FOREIGN KEY t_visit_ibfk_1;
ALTER TABLE `t_visit` ADD CONSTRAINT t_visit_ibfk_2 FOREIGN KEY (USER_ID) REFERENCES ad_user (USER_ID) ON UPDATE RESTRICT ON DELETE RESTRICT,
  ADD CONSTRAINT t_visit_ibfk_1 FOREIGN KEY (CUSTOMER_ID) REFERENCES m_customer (CUSTOMER_ID) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE `t_visit_line` CHARACTER SET tis620 COLLATE tis620_thai_ci;
ALTER TABLE `t_visit_line` DROP FOREIGN KEY t_visit_line_ibfk_3,
  DROP FOREIGN KEY t_visit_line_ibfk_1,
  DROP FOREIGN KEY t_visit_line_ibfk_2;
ALTER TABLE `t_visit_line` ADD CONSTRAINT t_visit_line_ibfk_3 FOREIGN KEY (UOM_ID) REFERENCES m_uom (UOM_ID) ON UPDATE RESTRICT ON DELETE RESTRICT,
  ADD CONSTRAINT t_visit_line_ibfk_1 FOREIGN KEY (VISIT_ID) REFERENCES t_visit (VISIT_ID) ON UPDATE RESTRICT ON DELETE RESTRICT,
  ADD CONSTRAINT t_visit_line_ibfk_2 FOREIGN KEY (PRODUCT_ID) REFERENCES m_product (PRODUCT_ID) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE `m_member_product` CHARACTER SET tis620 COLLATE tis620_thai_ci,
  CHANGE `MEMBER_PRODUCT_ID` MEMBER_PRODUCT_ID INTEGER(18) NOT NULL;
ALTER TABLE `m_member_product` DROP FOREIGN KEY m_member_product_ibfk_3,
  DROP FOREIGN KEY m_member_product_ibfk_1,
  DROP FOREIGN KEY m_member_product_ibfk_2;
ALTER TABLE `m_member_product` ADD CONSTRAINT m_member_product_ibfk_3 FOREIGN KEY (CUSTOMER_ID) REFERENCES m_customer (CUSTOMER_ID) ON UPDATE RESTRICT ON DELETE RESTRICT,
  ADD CONSTRAINT m_member_product_ibfk_1 FOREIGN KEY (PRODUCT_ID) REFERENCES m_product (PRODUCT_ID) ON UPDATE RESTRICT ON DELETE RESTRICT,
  ADD CONSTRAINT m_member_product_ibfk_2 FOREIGN KEY (UOM_ID) REFERENCES m_uom (UOM_ID) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE `m_address` CHANGE `ISACTIVE` ISACTIVE CHAR(1) CHARACTER SET tis620 COLLATE tis620_thai_ci NOT NULL DEFAULT 'Y',
  CHANGE `PURPOSE` PURPOSE CHAR(2) CHARACTER SET tis620 COLLATE tis620_thai_ci;
ALTER TABLE `m_address` DROP FOREIGN KEY m_address_ibfk_1,
  DROP FOREIGN KEY m_address_ibfk_2,
  DROP FOREIGN KEY m_address_ibfk_3;
ALTER TABLE `m_address` ADD CONSTRAINT m_address_ibfk_1 FOREIGN KEY (CUSTOMER_ID) REFERENCES m_customer (CUSTOMER_ID) ON UPDATE RESTRICT ON DELETE RESTRICT,
  ADD CONSTRAINT m_address_ibfk_2 FOREIGN KEY (PROVINCE_ID) REFERENCES m_province (PROVINCE_ID) ON UPDATE RESTRICT ON DELETE RESTRICT,
  ADD CONSTRAINT m_address_ibfk_3 FOREIGN KEY (DISTRICT_ID) REFERENCES m_district (DISTRICT_ID) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE `m_contact` CHANGE `ISACTIVE` ISACTIVE CHAR(1) CHARACTER SET tis620 COLLATE tis620_thai_ci NOT NULL DEFAULT 'Y';
ALTER TABLE `m_contact` DROP FOREIGN KEY m_contact_ibfk_1;
ALTER TABLE `m_contact` ADD CONSTRAINT m_contact_ibfk_1 FOREIGN KEY (CUSTOMER_ID) REFERENCES m_customer (CUSTOMER_ID) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE `m_customer` CHANGE `ISACTIVE` ISACTIVE CHAR(1) CHARACTER SET tis620 COLLATE tis620_thai_ci NOT NULL DEFAULT 'Y',
  CHANGE `CREDIT_CHECK` CREDIT_CHECK CHAR(1) CHARACTER SET tis620 COLLATE tis620_thai_ci DEFAULT 'N',
  CHANGE `PAYMENT_TERM` PAYMENT_TERM CHAR(5) CHARACTER SET tis620 COLLATE tis620_thai_ci,
  CHANGE `VAT_CODE` VAT_CODE CHAR(5) CHARACTER SET tis620 COLLATE tis620_thai_ci;
ALTER TABLE `m_customer` DROP FOREIGN KEY m_customer_ibfk_1,
  DROP FOREIGN KEY m_customer_ibfk_2;
ALTER TABLE `m_customer` ADD CONSTRAINT m_customer_ibfk_1 FOREIGN KEY (PRODUCT_CATEGORY_ID) REFERENCES m_product_category (PRODUCT_CATEGORY_ID) ON UPDATE RESTRICT ON DELETE RESTRICT,
  ADD CONSTRAINT m_customer_ibfk_2 FOREIGN KEY (USER_ID) REFERENCES ad_user (USER_ID) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE `t_visit` CHANGE `SALES_CLOSED` SALES_CLOSED CHAR(1) CHARACTER SET tis620 COLLATE tis620_thai_ci NOT NULL DEFAULT 'N',
  CHANGE `ISACTIVE` ISACTIVE CHAR(1) CHARACTER SET tis620 COLLATE tis620_thai_ci NOT NULL DEFAULT 'Y';
ALTER TABLE `t_visit` DROP FOREIGN KEY t_visit_ibfk_1,
  DROP FOREIGN KEY t_visit_ibfk_2;
ALTER TABLE `t_visit` ADD CONSTRAINT t_visit_ibfk_1 FOREIGN KEY (CUSTOMER_ID) REFERENCES m_customer (CUSTOMER_ID) ON UPDATE RESTRICT ON DELETE RESTRICT,
  ADD CONSTRAINT t_visit_ibfk_2 FOREIGN KEY (USER_ID) REFERENCES ad_user (USER_ID) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE `t_visit_line` CHANGE `LINE_NO` LINE_NO INTEGER(18),
  CHANGE `ISACTIVE` ISACTIVE CHAR(1) CHARACTER SET tis620 COLLATE tis620_thai_ci NOT NULL DEFAULT 'Y';
ALTER TABLE `t_visit_line` DROP FOREIGN KEY t_visit_line_ibfk_1,
  DROP FOREIGN KEY t_visit_line_ibfk_2,
  DROP FOREIGN KEY t_visit_line_ibfk_3;
ALTER TABLE `t_visit_line` ADD CONSTRAINT t_visit_line_ibfk_1 FOREIGN KEY (VISIT_ID) REFERENCES t_visit (VISIT_ID) ON UPDATE RESTRICT ON DELETE RESTRICT,
  ADD CONSTRAINT t_visit_line_ibfk_2 FOREIGN KEY (PRODUCT_ID) REFERENCES m_product (PRODUCT_ID) ON UPDATE RESTRICT ON DELETE RESTRICT,
  ADD CONSTRAINT t_visit_line_ibfk_3 FOREIGN KEY (UOM_ID) REFERENCES m_uom (UOM_ID) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE `m_customer` CHANGE `CHROLESTEROL` CHOLESTEROL DECIMAL(10,0),
  CHANGE `ORDER_AMOUNT_PERIOD` ORDER_AMOUNT_PERIOD VARCHAR(5),
  ADD RECOMMENDED_TYPE VARCHAR(5),
  ADD RECOMMENDED_ID INTEGER;
ALTER TABLE `m_customer` DROP FOREIGN KEY m_customer_ibfk_1,
  DROP FOREIGN KEY m_customer_ibfk_2;
ALTER TABLE `m_customer` ADD CONSTRAINT m_customer_ibfk_1 FOREIGN KEY (PRODUCT_CATEGORY_ID) REFERENCES m_product_category (PRODUCT_CATEGORY_ID) ON UPDATE RESTRICT ON DELETE RESTRICT,
  ADD CONSTRAINT m_customer_ibfk_2 FOREIGN KEY (USER_ID) REFERENCES ad_user (USER_ID) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE `m_customer` ADD SHIPPING_TIME VARCHAR(5) NOT NULL;
ALTER TABLE `m_customer` DROP FOREIGN KEY m_customer_ibfk_1,
  DROP FOREIGN KEY m_customer_ibfk_2;
ALTER TABLE `m_customer` ADD CONSTRAINT m_customer_ibfk_1 FOREIGN KEY (PRODUCT_CATEGORY_ID) REFERENCES m_product_category (PRODUCT_CATEGORY_ID) ON UPDATE RESTRICT ON DELETE RESTRICT,
  ADD CONSTRAINT m_customer_ibfk_2 FOREIGN KEY (USER_ID) REFERENCES ad_user (USER_ID) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE `m_customer` CHANGE `SHIPPING_TIME` SHIPPING_TIME VARCHAR(5);
ALTER TABLE `m_customer` DROP FOREIGN KEY m_customer_ibfk_1,
  DROP FOREIGN KEY m_customer_ibfk_2;
ALTER TABLE `m_customer` ADD CONSTRAINT m_customer_ibfk_1 FOREIGN KEY (PRODUCT_CATEGORY_ID) REFERENCES m_product_category (PRODUCT_CATEGORY_ID) ON UPDATE RESTRICT ON DELETE RESTRICT,
  ADD CONSTRAINT m_customer_ibfk_2 FOREIGN KEY (USER_ID) REFERENCES ad_user (USER_ID) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE `m_customer` CHANGE `CREATED` CREATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE `m_address` ADD CREATED TIMESTAMP,
  ADD CREATED_BY INT,
  ADD UPDATED TIMESTAMP DEFAULT NULL,
  ADD UPDATED_BY INT;
ALTER TABLE `m_address` DROP FOREIGN KEY m_address_ibfk_1,
  DROP FOREIGN KEY m_address_ibfk_2,
  DROP FOREIGN KEY m_address_ibfk_3;
ALTER TABLE `m_address` ADD CONSTRAINT m_address_ibfk_1 FOREIGN KEY (CUSTOMER_ID) REFERENCES m_customer (CUSTOMER_ID) ON UPDATE RESTRICT ON DELETE RESTRICT,
  ADD CONSTRAINT m_address_ibfk_2 FOREIGN KEY (PROVINCE_ID) REFERENCES m_province (PROVINCE_ID) ON UPDATE RESTRICT ON DELETE RESTRICT,
  ADD CONSTRAINT m_address_ibfk_3 FOREIGN KEY (DISTRICT_ID) REFERENCES m_district (DISTRICT_ID) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE `m_address` CHANGE `CREATED` CREATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE `m_contact` ADD CREATED TIMESTAMP,
  ADD CREATED_BY INTEGER,
  ADD UPDATED TIMESTAMP DEFAULT NULL,
  ADD UPDATED_BY INTEGER;
ALTER TABLE `m_contact` DROP FOREIGN KEY m_contact_ibfk_1;
ALTER TABLE `m_contact` ADD CONSTRAINT m_contact_ibfk_1 FOREIGN KEY (CUSTOMER_ID) REFERENCES m_customer (CUSTOMER_ID) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE `m_contact` CHANGE `CREATED` CREATED TIMESTAMP,
  CHANGE `UPDATED` UPDATED TIMESTAMP DEFAULT NULL;
ALTER TABLE `m_contact` DROP FOREIGN KEY m_contact_ibfk_1;
ALTER TABLE `m_contact` ADD CONSTRAINT m_contact_ibfk_1 FOREIGN KEY (CUSTOMER_ID) REFERENCES m_customer (CUSTOMER_ID) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE `m_contact` CHANGE `CREATED` CREATED TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE `m_member_product` ADD CREATED  TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE `m_member_product` ADD CREATED_BY  INTEGER;
ALTER TABLE `m_member_product` ADD UPDATED  TIMESTAMP DEFAULT NULL;
ALTER TABLE `m_member_product` ADD UPDATED_BY  INTEGER;
ALTER TABLE m_customer ADD COLUMN ROUND_TRIP  VARCHAR(5);
ALTER TABLE `m_customer` CHANGE `ROUND_TRIP` ROUND_TRIP VARCHAR(5) CHARACTER SET tis620 COLLATE tis620_thai_ci;
ALTER TABLE `m_customer` DROP FOREIGN KEY m_customer_ibfk_1,
  DROP FOREIGN KEY m_customer_ibfk_2;
ALTER TABLE `m_customer` ADD CONSTRAINT m_customer_ibfk_1 FOREIGN KEY (PRODUCT_CATEGORY_ID) REFERENCES m_product_category (PRODUCT_CATEGORY_ID) ON UPDATE RESTRICT ON DELETE RESTRICT,
  ADD CONSTRAINT m_customer_ibfk_2 FOREIGN KEY (USER_ID) REFERENCES ad_user (USER_ID) ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE t_visit ADD COLUMN INTERFACES  CHAR(1) DEFAULT 'N';

ALTER TABLE `m_address` ADD COLUMN PROVINCE_NAME VARCHAR(50) NULL;


ALTER TABLE `m_contact` ADD COLUMN PHONE2 VARCHAR(100) NOT NULL,
  ADD COLUMN MOBILE VARCHAR(100) NOT NULL,
  ADD COLUMN MOBILE2 VARCHAR(100) NOT NULL;
ALTER TABLE `m_contact` DROP FOREIGN KEY m_contact_ibfk_1;
ALTER TABLE `m_contact` ADD CONSTRAINT m_contact_ibfk_1 FOREIGN KEY (CUSTOMER_ID) REFERENCES m_customer (CUSTOMER_ID) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE `m_contact` CHANGE `PHONE2` PHONE2 VARCHAR(100),
  CHANGE `MOBILE` MOBILE VARCHAR(100),
  CHANGE `MOBILE2` MOBILE2 VARCHAR(100);
  
  
ALTER TABLE m_customer ADD COLUMN EXPIRED_DATE  DATE NULL;
ALTER TABLE m_customer ADD COLUMN AGE_MONTH  INTEGER NOT NULL DEFAULT 0;
ALTER TABLE m_customer ADD COLUMN INTERFACES CHAR(1) NOT NULL DEFAULT 'N';
ALTER TABLE m_customer ADD COLUMN PARTY_TYPE CHAR(1) DEFAULT NULL;
ALTER TABLE m_customer ADD COLUMN EXPORTED CHAR(1) NOT NULL DEFAULT 'N';
ALTER TABLE m_customer ADD COLUMN DELIVERY_GROUP  VARCHAR(5) DEFAULT NULL;
ALTER TABLE m_customer ADD COLUMN SHIPPING_TIME_TO  VARCHAR(5) DEFAULT NULL;
ALTER TABLE t_visit ADD COLUMN CUSTOMER_NAME VARCHAR(200) DEFAULT NULL;
ALTER TABLE t_visit ADD COLUMN ORDER_TYPE VARCHAR(5) DEFAULT NULL;
ALTER TABLE m_customer ADD COLUMN CREDITCARD_EXPIRED  VARCHAR(5) DEFAULT NULL;
ALTER TABLE m_customer CHANGE CREDITCARD_EXPIRED CREDITCARD_EXPIRED VARCHAR(5) DEFAULT NULL;
ALTER TABLE t_visit_line ADD COLUMN AMOUNT2 DECIMAL(10,0);

ALTER TABLE i_customer ADD COLUMN SHIPPING_TIME_TO  VARCHAR(5) DEFAULT NULL;
ALTER TABLE i_customer ADD COLUMN CREDITCARD_EXPIRED  VARCHAR(5) DEFAULT NULL;
ALTER TABLE i_customer ADD COLUMN ORDER_LINE_REMAIN  INTEGER DEFAULT 0;
ALTER TABLE i_customer ADD COLUMN START_NEXT_YEAR  DATE DEFAULT NULL;
ALTER TABLE i_customer ADD COLUMN PREPAID_NEXT_YEAR  DECIMAL(10,2) DEFAULT 0;
