
DROP INDEX XIF3T_ORDER_LINE ON T_ORDER_LINE
;



DROP INDEX XIF4T_ORDER_LINE ON T_ORDER_LINE
;



DROP INDEX XIF5T_ORDER_LINE ON T_ORDER_LINE
;



DROP INDEX XPKT_ORDER_LINE ON T_ORDER_LINE
;



DROP INDEX XIF1T_ORDER ON T_ORDER
;



DROP INDEX XIF2T_ORDER ON T_ORDER
;



DROP INDEX XIF3T_ORDER ON T_ORDER
;



DROP INDEX XPKT_ORDER ON T_ORDER
;




DROP TABLE T_ORDER_LINE
;




DROP TABLE T_ORDER
;



CREATE TABLE T_ORDER
(
	ORDER_ID              INTEGER NOT NULL,
	ORDER_DATE            DATE NULL,
	PAYMENT_TERM          VARCHAR(5) NULL,
	VAT_CODE              VARCHAR(5) NULL,
	TOTAL_AMOUNT          DECIMAL(10,2) NULL,
	VAT_AMOUNT            DECIMAL(10,2) NULL,
	NET_AMOUNT            DECIMAL(10,2) NULL,
	DOC_STATUS            CHAR(5) NULL,
	INTERFACES            CHAR(1) NULL DEFAULT 'N',
	SALES_ORDER_NO        VARCHAR(20) NULL,
	AR_INVOICE_NO         VARCHAR(20) NULL,
	CREATED               TIMESTAMP NULL,
	CREATED_BY            INTEGER NULL,
	UPDATED               TIMESTAMP NULL,
	UPDATED_BY            INTEGER NULL,
	USER_ID               INTEGER NULL,
	CUSTOMER_ID           INTEGER NULL,
	BILL_ADDRESS_ID       INTEGER NULL,
	SHIP_ADDRESS_ID       INTEGER NULL,
	CUSTOMER_NAME         VARCHAR(200) NULL,
	PAYMENT_METHOD        VARCHAR(5) NULL,
	SHIPPING_DAY          VARCHAR(5) NULL,
	SHIPPING_TIME         VARCHAR(5) NULL,
	ORDER_TYPE            VARCHAR(5) NULL,
	PAYMENT               CHAR(1) NOT NULL DEFAULT 'Y',
	VAT_RATE              DECIMAL(10,2) NULL,
	PRICELIST_ID          INTEGER NULL,
	ORDER_NO              VARCHAR(20) NOT NULL
)
;



CREATE UNIQUE INDEX XPKT_ORDER ON T_ORDER
(
	ORDER_ID
)
;



ALTER TABLE T_ORDER
	ADD  PRIMARY KEY (ORDER_ID)
;



CREATE INDEX XIF1T_ORDER ON T_ORDER
(
	CUSTOMER_ID
)
;



CREATE INDEX XIF2T_ORDER ON T_ORDER
(
	USER_ID
)
;



CREATE INDEX XIF3T_ORDER ON T_ORDER
(
	PRICELIST_ID
)
;



CREATE TABLE T_ORDER_LINE
(
	ORDER_LINE_ID         INTEGER NOT NULL,
	LINE_NO               INTEGER NULL,
	PRODUCT_ID            INTEGER NULL,
	UOM_ID                VARCHAR(20) NULL,
	ORDER_ID              INTEGER NULL,
	QTY                   DECIMAL(10,2) NULL,
	LINE_AMOUNT           DECIMAL(10,2) NULL,
	DISCOUNT              DECIMAL(10,2) NULL,
	TOTAL_AMOUNT          DECIMAL(10,2) NULL,
	REQUEST_DATE          DATE NULL,
	SHIPPING_DATE         DATE NULL,
	CREATED               TIMESTAMP NULL,
	CREATED_BY            INTEGER NULL,
	UPDATED               TIMESTAMP NULL,
	UPDATED_BY            INTEGER NULL
)
;



CREATE UNIQUE INDEX XPKT_ORDER_LINE ON T_ORDER_LINE
(
	ORDER_LINE_ID
)
;



ALTER TABLE T_ORDER_LINE
	ADD  PRIMARY KEY (ORDER_LINE_ID)
;



CREATE INDEX XIF3T_ORDER_LINE ON T_ORDER_LINE
(
	ORDER_ID
)
;



CREATE INDEX XIF4T_ORDER_LINE ON T_ORDER_LINE
(
	PRODUCT_ID
)
;



CREATE INDEX XIF5T_ORDER_LINE ON T_ORDER_LINE
(
	UOM_ID
)
;



ALTER TABLE T_ORDER
	ADD FOREIGN KEY R_26 (CUSTOMER_ID) REFERENCES M_CUSTOMER(CUSTOMER_ID)
;


ALTER TABLE T_ORDER
	ADD FOREIGN KEY R_27 (USER_ID) REFERENCES AD_USER(USER_ID)
;


ALTER TABLE T_ORDER
	ADD FOREIGN KEY R_40 (PRICELIST_ID) REFERENCES M_PRICELIST(PRICELIST_ID)
;



ALTER TABLE T_ORDER_LINE
	ADD FOREIGN KEY R_32 (ORDER_ID) REFERENCES T_ORDER(ORDER_ID)
;


ALTER TABLE T_ORDER_LINE
	ADD FOREIGN KEY R_30 (PRODUCT_ID) REFERENCES M_PRODUCT(PRODUCT_ID)
;


ALTER TABLE T_ORDER_LINE
	ADD FOREIGN KEY R_31 (UOM_ID) REFERENCES M_UOM(UOM_ID)
;

ALTER TABLE `T_ORDER` RENAME `t_order`;

ALTER TABLE `t_order` ENGINE = InnoDB CHARACTER SET tis620 COLLATE tis620_thai_ci,
  CHANGE `PAYMENT_TERM` PAYMENT_TERM VARCHAR(5) CHARACTER SET tis620 COLLATE tis620_thai_ci,
  CHANGE `VAT_CODE` VAT_CODE VARCHAR(5) CHARACTER SET tis620 COLLATE tis620_thai_ci,
  CHANGE `DOC_STATUS` DOC_STATUS CHAR(5) CHARACTER SET tis620 COLLATE tis620_thai_ci,
  CHANGE `INTERFACES` INTERFACES CHAR(1) CHARACTER SET tis620 COLLATE tis620_thai_ci DEFAULT 'N',
  CHANGE `SALES_ORDER_NO` SALES_ORDER_NO VARCHAR(20) CHARACTER SET tis620 COLLATE tis620_thai_ci,
  CHANGE `AR_INVOICE_NO` AR_INVOICE_NO VARCHAR(20) CHARACTER SET tis620 COLLATE tis620_thai_ci,
  CHANGE `CUSTOMER_NAME` CUSTOMER_NAME VARCHAR(200) CHARACTER SET tis620 COLLATE tis620_thai_ci,
  CHANGE `PAYMENT_METHOD` PAYMENT_METHOD VARCHAR(5) CHARACTER SET tis620 COLLATE tis620_thai_ci,
  CHANGE `SHIPPING_DAY` SHIPPING_DAY VARCHAR(5) CHARACTER SET tis620 COLLATE tis620_thai_ci,
  CHANGE `SHIPPING_TIME` SHIPPING_TIME VARCHAR(5) CHARACTER SET tis620 COLLATE tis620_thai_ci,
  CHANGE `ORDER_TYPE` ORDER_TYPE VARCHAR(5) CHARACTER SET tis620 COLLATE tis620_thai_ci,
  CHANGE `PAYMENT` PAYMENT CHAR(1) CHARACTER SET tis620 COLLATE tis620_thai_ci DEFAULT 'Y',
  CHANGE `ORDER_NO` ORDER_NO VARCHAR(20) CHARACTER SET tis620 COLLATE tis620_thai_ci NOT NULL;
ALTER TABLE `t_order` CHANGE `CREATED` CREATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE `T_ORDER_LINE` RENAME `t_order_line`;
ALTER TABLE `t_order_line` ENGINE = InnoDB CHARACTER SET tis620 COLLATE tis620_thai_ci,
  CHANGE `PRODUCT_ID` PRODUCT_ID INT(11) NOT NULL,
  CHANGE `UOM_ID` UOM_ID VARCHAR(20) NOT NULL,
  CHANGE `ORDER_ID` ORDER_ID INT(11) NOT NULL,
  CHANGE `QTY` QTY DECIMAL(10,2) DEFAULT '0',
  CHANGE `LINE_AMOUNT` LINE_AMOUNT DECIMAL(10,2) DEFAULT '0',
  CHANGE `DISCOUNT` DISCOUNT DECIMAL(10,2) DEFAULT '0',
  CHANGE `TOTAL_AMOUNT` TOTAL_AMOUNT DECIMAL(10,2) DEFAULT '0';
ALTER TABLE `t_order_line` ADD PRICE DECIMAL(10,2) NOT NULL DEFAULT '0';
ALTER TABLE `t_order_line` CHANGE `CREATED` CREATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE `t_order_line` ADD PROMOTION CHAR(1) NULL DEFAULT 'N';
ALTER TABLE `t_order` ADD COLUMN ORDER_TIME VARCHAR(5) DEFAULT NULL;





DROP TABLE T_RECEIPT_LINE
;




DROP TABLE T_RECEIPT
;



CREATE TABLE T_RECEIPT
(
	RECEIPT_ID            INTEGER NOT NULL,
	RECEIPT_NO            VARCHAR(20) NOT NULL,
	RECEIPT_DATE          DATE NULL,
	ORDER_TYPE            VARCHAR(5) NULL,
	CUSTOMER_ID           INTEGER NULL,
	CUSTOMER_NAME         VARCHAR(200) NULL,
	PAYMENT_METHOD        VARCHAR(5) NULL,
	BANK                  VARCHAR(100) NULL,
	CHEQUE_NO             VARCHAR(20) NULL,
	CHEQUE_DATE           DATE NULL,
	RECEIPT_AMOUNT        DECIMAL(10,2) NULL,
	INTERFACES            CHAR(1) NOT NULL DEFAULT 'N',
	DOC_STATUS            CHAR(5) NULL,
	USER_ID               INTEGER NULL,
	CREATED               DATETIME NULL,
	CREATED_BY            INTEGER NULL,
	UPDATED               DATETIME NULL,
	UPDATED_BY            INTEGER NULL
)
;



CREATE UNIQUE INDEX XPKT_RECEIPT ON T_RECEIPT
(
	RECEIPT_ID
)
;



ALTER TABLE T_RECEIPT
	ADD  PRIMARY KEY (RECEIPT_ID)
;



CREATE INDEX XIF1T_RECEIPT ON T_RECEIPT
(
	USER_ID
)
;



CREATE INDEX XIF2T_RECEIPT ON T_RECEIPT
(
	CUSTOMER_ID
)
;



CREATE TABLE T_RECEIPT_LINE
(
	RECEIPT_LINE_ID       INTEGER NULL,
	LINE_NO               INTEGER NULL,
	RECEIPT_ID            INTEGER NULL,
	AR_INVOICE_NO         VARCHAR(20) NULL,
	SALES_ORDER_NO        VARCHAR(20) NULL,
	INVOICE_AMOUNT        DECIMAL(10,2) NULL,
	CREDIT_AMOUNT         DECIMAL(10,2) NULL,
	PAID_AMOUNT           DECIMAL(10,2) NULL,
	REMAIN_AMOUNT         DECIMAL(10,2) NULL,
	ORDER_ID              INTEGER NULL
)
;



CREATE UNIQUE INDEX XPKT_RECEIPT_LINE ON T_RECEIPT_LINE
(
	RECEIPT_LINE_ID
)
;



ALTER TABLE T_RECEIPT_LINE
	ADD  PRIMARY KEY (RECEIPT_LINE_ID)
;



CREATE INDEX XIF1T_RECEIPT_LINE ON T_RECEIPT_LINE
(
	RECEIPT_ID
)
;



CREATE INDEX XIF2T_RECEIPT_LINE ON T_RECEIPT_LINE
(
	ORDER_ID
)
;



ALTER TABLE T_RECEIPT
	ADD FOREIGN KEY R_72 (USER_ID) REFERENCES AD_USER(USER_ID)
;


ALTER TABLE T_RECEIPT
	ADD FOREIGN KEY R_74 (CUSTOMER_ID) REFERENCES M_CUSTOMER(CUSTOMER_ID)
;



ALTER TABLE T_RECEIPT_LINE
	ADD FOREIGN KEY R_75 (RECEIPT_ID) REFERENCES T_RECEIPT(RECEIPT_ID)
;


ALTER TABLE T_RECEIPT_LINE
	ADD FOREIGN KEY R_76 (ORDER_ID) REFERENCES T_ORDER(ORDER_ID)
;


ALTER TABLE `t_receipt` CHARACTER SET tis620 COLLATE tis620_thai_ci,
  CHANGE `RECEIPT_NO` RECEIPT_NO VARCHAR(20) CHARACTER SET tis620 COLLATE tis620_thai_ci NOT NULL,
  CHANGE `ORDER_TYPE` ORDER_TYPE VARCHAR(5) CHARACTER SET tis620 COLLATE tis620_thai_ci,
  CHANGE `CUSTOMER_NAME` CUSTOMER_NAME VARCHAR(200) CHARACTER SET tis620 COLLATE tis620_thai_ci,
  CHANGE `PAYMENT_METHOD` PAYMENT_METHOD VARCHAR(5) CHARACTER SET tis620 COLLATE tis620_thai_ci,
  CHANGE `BANK` BANK VARCHAR(100) CHARACTER SET tis620 COLLATE tis620_thai_ci,
  CHANGE `CHEQUE_NO` CHEQUE_NO VARCHAR(20) CHARACTER SET tis620 COLLATE tis620_thai_ci,
  CHANGE `INTERFACES` INTERFACES CHAR(1) CHARACTER SET tis620 COLLATE tis620_thai_ci NOT NULL DEFAULT 'N',
  CHANGE `DOC_STATUS` DOC_STATUS CHAR(5) CHARACTER SET tis620 COLLATE tis620_thai_ci;
ALTER TABLE `t_receipt` DROP FOREIGN KEY t_receipt_ibfk_2,
  DROP FOREIGN KEY t_receipt_ibfk_1;
ALTER TABLE `t_receipt` ADD CONSTRAINT t_receipt_ibfk_2 FOREIGN KEY (CUSTOMER_ID) REFERENCES m_customer (CUSTOMER_ID) ON UPDATE RESTRICT ON DELETE RESTRICT,
  ADD CONSTRAINT t_receipt_ibfk_1 FOREIGN KEY (USER_ID) REFERENCES ad_user (USER_ID) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE `t_receipt_line` CHARACTER SET tis620 COLLATE tis620_thai_ci,
  CHANGE `AR_INVOICE_NO` AR_INVOICE_NO VARCHAR(20) CHARACTER SET tis620 COLLATE tis620_thai_ci,
  CHANGE `SALES_ORDER_NO` SALES_ORDER_NO VARCHAR(20) CHARACTER SET tis620 COLLATE tis620_thai_ci;
ALTER TABLE `t_receipt_line` DROP FOREIGN KEY t_receipt_line_ibfk_2,
  DROP FOREIGN KEY t_receipt_line_ibfk_1;
ALTER TABLE `t_receipt_line` ADD CONSTRAINT t_receipt_line_ibfk_2 FOREIGN KEY (ORDER_ID) REFERENCES t_order (ORDER_ID) ON UPDATE RESTRICT ON DELETE RESTRICT,
  ADD CONSTRAINT t_receipt_line_ibfk_1 FOREIGN KEY (RECEIPT_ID) REFERENCES t_receipt (RECEIPT_ID) ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE t_receipt_line ADD COLUMN UPDATED  DATETIME;

ALTER TABLE t_receipt_line ADD COLUMN UPDATED_BY  INTEGER;

ALTER TABLE t_receipt_line ADD CREATED_BY  INTEGER;

ALTER TABLE t_receipt_line ADD CREATED  DATETIME;

ALTER TABLE `t_receipt` CHANGE `CREATED` CREATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE `t_receipt_line` CHANGE `CREATED` CREATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE t_order_line ADD COLUMN AR_INVOICE_NO  VARCHAR(20) DEFAULT NULL;
ALTER TABLE t_order_line ADD COLUMN PAYMENT  CHAR(1) NOT NULL DEFAULT 'N';
ALTER TABLE t_receipt ADD COLUMN CREDIT_CARD_TYPE  VARCHAR(5) DEFAULT NULL;
ALTER TABLE t_receipt_line ADD COLUMN DESCRIPTION  VARCHAR(200) DEFAULT NULL;
ALTER TABLE t_receipt ADD COLUMN DESCRIPTION  VARCHAR(200) DEFAULT NULL;
ALTER TABLE t_receipt ADD COLUMN PREPAID CHAR(1) NOT NULL DEFAULT 'N';
ALTER TABLE t_order_line ADD COLUMN VAT_AMOUNT  DECIMAL(10,2) DEFAULT 0;





DROP INDEX XIF1T_RECEIPT_MATCH ON T_RECEIPT_MATCH
;



DROP INDEX XIF2T_RECEIPT_MATCH ON T_RECEIPT_MATCH
;



DROP INDEX XPKT_RECEIPT_MATCH ON T_RECEIPT_MATCH
;



DROP INDEX XIF1T_RECEIPT_BY ON T_RECEIPT_BY
;



DROP INDEX XPKT_RECEIPT_BY ON T_RECEIPT_BY
;




DROP TABLE T_RECEIPT_MATCH
;




DROP TABLE T_RECEIPT_BY
;



CREATE TABLE T_RECEIPT_BY
(
	RECEIPT_BY_ID         INTEGER NOT NULL,
	PAYMENT_METHOD        VARCHAR(5) NULL,
	BANK                  VARCHAR(100) NULL,
	CHEQUE_NO             VARCHAR(20) NULL,
	CHEQUE_DATE           DATE NULL,
	RECEIPT_AMOUNT        DECIMAL(10,2) NULL,
	CREDIT_CARD_TYPE      VARCHAR(5) NULL,
	PAID_AMOUNT           DECIMAL(10,2) NULL,
	REMAIN_AMOUNT         DECIMAL(10,2) NULL,
	RECEIPT_ID            INTEGER NOT NULL,
	CREATED_BY            INTEGER NULL,
	UPDATED               DATETIME NULL,
	UPDATED_BY            INTEGER NULL,
	CREATED               DATETIME NULL
)
;



CREATE UNIQUE INDEX XPKT_RECEIPT_BY ON T_RECEIPT_BY
(
	RECEIPT_BY_ID
)
;



ALTER TABLE T_RECEIPT_BY
	ADD  PRIMARY KEY (RECEIPT_BY_ID)
;



CREATE INDEX XIF1T_RECEIPT_BY ON T_RECEIPT_BY
(
	RECEIPT_ID
)
;



CREATE TABLE T_RECEIPT_MATCH
(
	RECEIPT_MATCH_ID      INTEGER NOT NULL,
	RECEIPT_BY_ID         INTEGER NULL,
	RECEIPT_LINE_ID       INTEGER NULL,
	PAID_AMOUNT           DECIMAL(10,2) NULL,
	CREATED               DATETIME NULL,
	CREATED_BY            INTEGER NULL,
	UPDATED               DATETIME NULL,
	UPDATED_BY            INTEGER NULL
)
;



CREATE UNIQUE INDEX XPKT_RECEIPT_MATCH ON T_RECEIPT_MATCH
(
	RECEIPT_MATCH_ID
)
;



ALTER TABLE T_RECEIPT_MATCH
	ADD  PRIMARY KEY (RECEIPT_MATCH_ID)
;



CREATE INDEX XIF1T_RECEIPT_MATCH ON T_RECEIPT_MATCH
(
	RECEIPT_BY_ID
)
;



CREATE INDEX XIF2T_RECEIPT_MATCH ON T_RECEIPT_MATCH
(
	RECEIPT_LINE_ID
)
;



ALTER TABLE T_RECEIPT_BY
	ADD FOREIGN KEY R_90 (RECEIPT_ID) REFERENCES T_RECEIPT(RECEIPT_ID)
;



ALTER TABLE T_RECEIPT_MATCH
	ADD FOREIGN KEY R_91 (RECEIPT_BY_ID) REFERENCES T_RECEIPT_BY(RECEIPT_BY_ID)
;


ALTER TABLE T_RECEIPT_MATCH
	ADD FOREIGN KEY R_92 (RECEIPT_LINE_ID) REFERENCES T_RECEIPT_LINE(RECEIPT_LINE_ID)
;

ALTER TABLE t_receipt_by CHARACTER SET tis620 COLLATE tis620_thai_ci,
 DROP FOREIGN KEY t_receipt_by_ibfk_1,
 CHANGE PAYMENT_METHOD PAYMENT_METHOD VARCHAR(5) CHARACTER SET tis620 COLLATE tis620_thai_ci,
 CHANGE BANK BANK VARCHAR(100) CHARACTER SET tis620 COLLATE tis620_thai_ci,
 CHANGE CHEQUE_NO CHEQUE_NO VARCHAR(20) CHARACTER SET tis620 COLLATE tis620_thai_ci,
 CHANGE CREDIT_CARD_TYPE CREDIT_CARD_TYPE VARCHAR(5) CHARACTER SET tis620 COLLATE tis620_thai_ci;
ALTER TABLE t_receipt_by
 ADD CONSTRAINT t_receipt_by_ibfk_1 FOREIGN KEY (RECEIPT_ID) REFERENCES t_receipt (RECEIPT_ID) ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE `t_receipt_by` CHANGE `CREATED` CREATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE `t_receipt_match` CHANGE `CREATED` CREATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE t_receipt_match ADD COLUMN RECEIPT_ID  INTEGER;
ALTER TABLE t_receipt ADD COLUMN APPLY_AMOUNT DECIMAL(10,2);
ALTER TABLE t_receipt_by ADD COLUMN SEED_ID VARCHAR(30) DEFAULT NULL;
ALTER TABLE t_order ADD COLUMN EXPORTED CHAR(1) NOT NULL DEFAULT 'N';
ALTER TABLE t_receipt ADD COLUMN EXPORTED CHAR(1) NOT NULL DEFAULT 'N';
ALTER TABLE t_visit ADD COLUMN EXPORTED CHAR(1) NOT NULL DEFAULT 'N';
ALTER TABLE t_receipt_by CHANGE CREDIT_CARD_TYPE CREDIT_CARD_TYPE VARCHAR(20);
ALTER TABLE t_order_line ADD COLUMN TRIP_NO INT DEFAULT 0;
ALTER TABLE t_receipt_by ADD COLUMN CREDITCARD_EXPIRED  DATE DEFAULT NULL;
ALTER TABLE t_receipt_by CHANGE CREDITCARD_EXPIRED CREDITCARD_EXPIRED VARCHAR(5) DEFAULT NULL;