

DROP TABLE M_INVENTORY
;




DROP TABLE M_INVENTORY_TRANSACTION
;



CREATE TABLE M_INVENTORY
(
	INVENTORY_ID          INTEGER NOT NULL,
	USER_ID               INTEGER NULL,
	PRODUCT_ID            INTEGER NULL,
	UOM_ID                VARCHAR(20) NULL,
	AVAILABLE_QTY         DECIMAL(10,2) NULL
)
;



CREATE UNIQUE INDEX XPKM_INVENTORY ON M_INVENTORY
(
	INVENTORY_ID
)
;



ALTER TABLE M_INVENTORY
	ADD  PRIMARY KEY (INVENTORY_ID)
;



CREATE INDEX XIF1M_INVENTORY ON M_INVENTORY
(
	USER_ID
)
;



CREATE INDEX XIF2M_INVENTORY ON M_INVENTORY
(
	PRODUCT_ID
)
;



CREATE INDEX XIF3M_INVENTORY ON M_INVENTORY
(
	UOM_ID
)
;



CREATE TABLE M_INVENTORY_TRANSACTION
(
	TRANSACTION_ID        INTEGER NULL,
	TRANSACTION_TYPE      VARCHAR(5) NULL,
	USER_ID               INTEGER NULL,
	PRODUCT_ID            INTEGER NULL,
	UOM_ID                VARCHAR(20) NULL,
	QTY                   DECIMAL(10,2) NULL,
	MOVEMENT_DATE         DATETIME NULL
)
;



CREATE UNIQUE INDEX XPKM_INVENTORY_TRANSACTION ON M_INVENTORY_TRANSACTION
(
	TRANSACTION_ID
)
;



ALTER TABLE M_INVENTORY_TRANSACTION
	ADD  PRIMARY KEY (TRANSACTION_ID)
;



CREATE INDEX XIF1M_INVENTORY_TRANSACTION ON M_INVENTORY_TRANSACTION
(
	USER_ID
)
;



CREATE INDEX XIF2M_INVENTORY_TRANSACTION ON M_INVENTORY_TRANSACTION
(
	PRODUCT_ID
)
;



CREATE INDEX XIF3M_INVENTORY_TRANSACTION ON M_INVENTORY_TRANSACTION
(
	UOM_ID
)
;



ALTER TABLE M_INVENTORY
	ADD FOREIGN KEY R_41 (USER_ID) REFERENCES AD_USER(USER_ID)
;


ALTER TABLE M_INVENTORY
	ADD FOREIGN KEY R_42 (PRODUCT_ID) REFERENCES M_PRODUCT(PRODUCT_ID)
;


ALTER TABLE M_INVENTORY
	ADD FOREIGN KEY R_43 (UOM_ID) REFERENCES M_UOM(UOM_ID)
;



ALTER TABLE M_INVENTORY_TRANSACTION
	ADD FOREIGN KEY R_44 (USER_ID) REFERENCES AD_USER(USER_ID)
;


ALTER TABLE M_INVENTORY_TRANSACTION
	ADD FOREIGN KEY R_45 (PRODUCT_ID) REFERENCES M_PRODUCT(PRODUCT_ID)
;


ALTER TABLE M_INVENTORY_TRANSACTION
	ADD FOREIGN KEY R_46 (UOM_ID) REFERENCES M_UOM(UOM_ID)
;


/**ON-HAND new*/


ALTER TABLE ad_user ADD COLUMN SUB_INVENTORY_ID  INTEGER;


CREATE TABLE M_SUB_INVENTORY
(
	SUB_INVENTORY_ID      INTEGER NOT NULL,
	NAME                  VARCHAR(100) NULL,
	DESCRIPTION           VARCHAR(255) NULL,
	TYPE                  VARCHAR(5) NULL,
	TERRITORY             VARCHAR(5) NULL,
	ISACTIVE              CHAR(1) NULL DEFAULT 'Y'
)
;



CREATE UNIQUE INDEX XPKM_SUB_INVENTORY ON M_SUB_INVENTORY
(
	SUB_INVENTORY_ID
)
;



ALTER TABLE M_SUB_INVENTORY
	ADD  PRIMARY KEY (SUB_INVENTORY_ID)
;



CREATE TABLE M_INVENTORY_ONHAND
(
	USER_ID               INTEGER NULL,
	SUB_INVENTORY_ID      INTEGER NULL,
	INVENTORY_ITEM_ID     INTEGER NULL,
	INVENTORY_ONHAND_ID   INTEGER NOT NULL,
	UOM_ID                VARCHAR(20) NULL,
	AVAILABLE_QTY         DECIMAL(10,2) NULL
)
;



CREATE UNIQUE INDEX XPKM_INVENTORY_ONHAND ON M_INVENTORY_ONHAND
(
	INVENTORY_ONHAND_ID
)
;



ALTER TABLE M_INVENTORY_ONHAND
	ADD  PRIMARY KEY (INVENTORY_ONHAND_ID)
;



ALTER TABLE M_INVENTORY_ONHAND
	ADD FOREIGN KEY R_77 (USER_ID) REFERENCES AD_USER(USER_ID)
;


ALTER TABLE M_INVENTORY_ONHAND
	ADD FOREIGN KEY R_78 (SUB_INVENTORY_ID) REFERENCES M_SUB_INVENTORY(SUB_INVENTORY_ID)
;


ALTER TABLE M_INVENTORY_ONHAND
	ADD FOREIGN KEY R_79 (INVENTORY_ITEM_ID) REFERENCES M_PRODUCT(PRODUCT_ID)
;


ALTER TABLE M_INVENTORY_ONHAND
	ADD FOREIGN KEY R_80 (UOM_ID) REFERENCES M_UOM(UOM_ID)
;

ALTER TABLE m_sub_inventory ADD COLUMN ORGANIZATION_ID  INTEGER DEFAULT NULL;


ALTER TABLE AD_USER DROP SUB_INVENTORY_ID;



CREATE TABLE M_SALES_INVENTORY
(
	SUB_INVENTORY_ID      INTEGER NOT NULL,
	USER_ID               INTEGER NOT NULL
)
;



ALTER TABLE M_SALES_INVENTORY
	ADD  PRIMARY KEY (SUB_INVENTORY_ID,USER_ID)
;



ALTER TABLE M_SALES_INVENTORY
	ADD FOREIGN KEY R_83 (SUB_INVENTORY_ID) REFERENCES M_SUB_INVENTORY(SUB_INVENTORY_ID)
;


ALTER TABLE M_SALES_INVENTORY
	ADD FOREIGN KEY R_84 (USER_ID) REFERENCES AD_USER(USER_ID)
;


ALTER TABLE m_sub_inventory
 CHANGE TYPE TYPE VARCHAR(20);
