

DROP TABLE M_TRIP
;



CREATE TABLE M_TRIP
(
	TRIP_ID               INTEGER NULL,
	YEAR                  CHAR(2) NULL,
	MONTH                 CHAR(2) NULL,
	DAY                   CHAR(2) NULL,
	CUSTOMER_ID           INTEGER NULL,
	USER_ID               INTEGER NULL
)
;



CREATE UNIQUE INDEX XPKT_TRIP ON M_TRIP
(
	TRIP_ID
)
;



ALTER TABLE M_TRIP
	ADD  PRIMARY KEY (TRIP_ID)
;



CREATE INDEX XIF1T_TRIP ON M_TRIP
(
	CUSTOMER_ID
)
;



CREATE INDEX XIF2T_TRIP ON M_TRIP
(
	USER_ID
)
;



ALTER TABLE M_TRIP
	ADD FOREIGN KEY R_53 (CUSTOMER_ID) REFERENCES M_CUSTOMER(CUSTOMER_ID)
;


ALTER TABLE M_TRIP
	ADD FOREIGN KEY R_54 (USER_ID) REFERENCES AD_USER(USER_ID)
;


ALTER TABLE `M_TRIP` RENAME `m_trip`;
ALTER TABLE `m_trip` ENGINE = InnoDB CHARACTER SET tis620 COLLATE tis620_thai_ci,
  CHANGE `YEAR` YEAR CHAR(2) CHARACTER SET tis620 COLLATE tis620_thai_ci,
  CHANGE `MONTH` MONTH CHAR(2) CHARACTER SET tis620 COLLATE tis620_thai_ci,
  CHANGE `DAY` DAY CHAR(2) CHARACTER SET tis620 COLLATE tis620_thai_ci;
ALTER TABLE `m_trip` CHANGE `YEAR` YEAR CHAR(4) CHARACTER SET tis620 COLLATE tis620_thai_ci;
ALTER TABLE `m_trip` DROP FOREIGN KEY m_trip_ibfk_1,
  DROP FOREIGN KEY m_trip_ibfk_2;
ALTER TABLE `m_trip` ADD CONSTRAINT m_trip_ibfk_1 FOREIGN KEY (CUSTOMER_ID) REFERENCES m_customer (CUSTOMER_ID) ON UPDATE RESTRICT ON DELETE RESTRICT,
  ADD CONSTRAINT m_trip_ibfk_2 FOREIGN KEY (USER_ID) REFERENCES ad_user (USER_ID) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE m_trip ADD COLUMN CREATED  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE m_trip ADD COLUMN CREATED_BY  INTEGER;
ALTER TABLE m_trip ADD COLUMN UPDATED  TIMESTAMP NULL;
ALTER TABLE m_trip ADD COLUMN UPDATED_BY  INTEGER;
ALTER TABLE m_trip ADD COLUMN LINE_NO  INTEGER;