
CREATE TABLE T_CREDIT_NOTE
(
	CREDIT_NOTE_ID        INTEGER NOT NULL,
	CREDIT_NOTE_NO        VARCHAR(20) NOT NULL,
	DOCUMENT_DATE         DATE NULL,
	AR_INVOICE_NO         VARCHAR(20) NOT NULL,
	TOTAL_AMOUNT          DECIMAL(10,2) NULL,
	ACTIVE                CHAR(1) NOT NULL DEFAULT 'Y'
)engine=innodb default charset=tis620
;



CREATE UNIQUE INDEX XPKT_CREDIT_NOTE ON T_CREDIT_NOTE
(
	CREDIT_NOTE_ID
)
;



ALTER TABLE T_CREDIT_NOTE
	ADD  PRIMARY KEY (CREDIT_NOTE_ID)
;


CREATE TABLE `t_receipt_cn` (
  `RECEIPT_CN_ID` int(11) NOT NULL,
  `CREDIT_NOTE_ID` int(11) NOT NULL,
  `RECEIPT_ID` int(11) NOT NULL,
  `CREATED` timestamp NOT NULL default CURRENT_TIMESTAMP,
  `CREATED_BY` int(11) NOT NULL,
  `UPDATED` timestamp NULL default NULL,
  `UPDATED_BY` int(11) default NULL,
  PRIMARY KEY  (`RECEIPT_CN_ID`),
  UNIQUE KEY `XPKT_RECEIPT_CN` (`RECEIPT_CN_ID`),
  KEY `XIF1T_RECEIPT_CN` (`CREDIT_NOTE_ID`),
  KEY `XIF2T_RECEIPT_CN` (`RECEIPT_ID`),
  CONSTRAINT `t_receipt_cn_ibfk_2` FOREIGN KEY (`RECEIPT_ID`) REFERENCES `t_receipt` (`RECEIPT_ID`),
  CONSTRAINT `t_receipt_cn_ibfk_1` FOREIGN KEY (`CREDIT_NOTE_ID`) REFERENCES `t_credit_note` (`CREDIT_NOTE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=tis620;


