ALTER TABLE `m_inventory` CHARACTER SET tis620 COLLATE tis620_thai_ci,
  CHANGE `UOM_ID` UOM_ID VARCHAR(20) CHARACTER SET tis620 COLLATE tis620_thai_ci;
ALTER TABLE `m_inventory` DROP FOREIGN KEY m_inventory_ibfk_1,
  DROP FOREIGN KEY m_inventory_ibfk_2,
  DROP FOREIGN KEY m_inventory_ibfk_3;
ALTER TABLE `m_inventory` ADD CONSTRAINT m_inventory_ibfk_1 FOREIGN KEY (USER_ID) REFERENCES ad_user (USER_ID) ON UPDATE RESTRICT ON DELETE RESTRICT,
  ADD CONSTRAINT m_inventory_ibfk_2 FOREIGN KEY (PRODUCT_ID) REFERENCES m_product (PRODUCT_ID) ON UPDATE RESTRICT ON DELETE RESTRICT,
  ADD CONSTRAINT m_inventory_ibfk_3 FOREIGN KEY (UOM_ID) REFERENCES m_uom (UOM_ID) ON UPDATE RESTRICT ON DELETE RESTRICT;
