ALTER TABLE i_customer ADD COLUMN SHIPPING_TIME_TO  VARCHAR(5) DEFAULT NULL;
ALTER TABLE i_customer ADD COLUMN CREDITCARD_EXPIRED  VARCHAR(5) DEFAULT NULL;
ALTER TABLE i_customer ADD COLUMN ORDER_LINE_REMAIN  INTEGER DEFAULT 0;
ALTER TABLE i_customer ADD COLUMN START_NEXT_YEAR  DATE DEFAULT NULL;
ALTER TABLE i_customer ADD COLUMN PREPAID_NEXT_YEAR  DECIMAL(10,2) DEFAULT 0;
ALTER TABLE m_modifier_line CHANGE VALUE VALUE DECIMAL(15,5);